hmcts/ia-ccd-e2e-tests

e2e/fields/complex-field-finders/ccd-write-collection-finder.ts
https://github.com/hmcts/ccd-case-management-web/pull/550
This change updates the CcdWriteCollectionFinder reference to work with CCD UI changes in the above CCD pull request.
```
[x] Yes
[ ] No
```
=> Updated element references to work with the new CCD UI changes

e2e/features/case-list.feature, e2e/features/case-progression.feature, e2e/features/generate-hearing-ready-bundle.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/stepDefinitions/service/generate-hearing-bundle.steps.ts, e2e/flows/generate-hearing-bundle.flow.ts
=> Ria 574 start decisions and reasons

e2e/features/case-progression.feature
[RIA-1534](https://tools.hmcts.net/jira/browse/RIA-1534)
pre hearing overview tab with link to the next step
```
[ ] Yes
[x] No
```
=> RIA-1534 pre hearing overview tab link

e2e/features/case-progression.feature, e2e/features/generate-decisions-and-reasons.feature, e2e/features/stepDefinitions/service/start-decision-and-reasons.steps.ts, e2e/flows/start-decision-and-reasons.flow.ts
=> Ria 1152 & 1153 generate decision and reasons

e2e/features/generate-decisions-and-reasons.feature
[RIA-1540](https://tools.hmcts.net/jira/browse/RIA-1540)
[RIA-1544](https://tools.hmcts.net/jira/browse/RIA-1544)
Overview tabs
```
[ ] Yes
[x] No
```
=> RIA-1540-RIA-1544 Overview tabs

e2e/features/case-progression.feature, e2e/features/generate-decisions-and-reasons.feature, e2e/features/send-decision-and-reasons.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/stepDefinitions/service/generate-decision-and-reasons.steps.ts, e2e/features/stepDefinitions/service/send-decision-and-reasons.steps.ts, e2e/flows/generate-decision-and-reasons.flow.ts, e2e/flows/send-decision-and-reasons.flow.ts, e2e/pages/any.page.ts
[RIA-1154](https://tools.hmcts.net/jira/browse/RIA-1154)
draft tests for send decision and reasons state
branch was created based on RIA-1152 & RIA-1153 branch
```
[ ] Yes
[x] No
```
=> RIA-1154 send decision and reasons

e2e/features/case-progression.feature, e2e/features/generate-hearing-bundle.feature, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/submit-appeal-out-of-time.feature, e2e/flows/generate-hearing-bundle.flow.ts
[RIA-986](https://tools.hmcts.net/jira/browse/RIA-986)
case officer out of time image in overview tab
```
[ ] Yes
[x] No
```
=> RIA-986 case officer out of time image

e2e/features/add-case-note.feature, e2e/features/case-progression.feature, e2e/features/generate-decisions-and-reasons.feature
=> Ria 575 add case note

e2e/features/generate-skeleton-bundle.feature
[RIA-481](https://tools.hmcts.net/jira/browse/RIA-481)
skeleton bundle test
```
[ ] Yes
[x] No
```
=> RIA-481 skeleton bundle test

README.md, bin/create-users.sh, e2e/features/idam-sign-in.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/flows/authentication.flow.ts, e2e/ia.conf.js
[RIA-1608](https://tools.hmcts.net/jira/browse/RIA-1608)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1608 authentication for admin role

bin/create-users.sh, e2e/features/case-list.feature, e2e/features/case-progression.feature, e2e/features/generate-decisions-and-reasons.feature, e2e/features/idam-sign-in.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/flows/authentication.flow.ts, e2e/ia.conf.js
[RIA-1611](https://tools.hmcts.net/jira/browse/RIA-1611)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-1611-view-dashboard

e2e/features/add-addendum-evidence.feature, e2e/ia.conf.js
[RIA-1603](https://tools.hmcts.net/jira/browse/RIA-1603)
branch created based on RIA-1608
addendum tests
```
[ ] Yes
[x] No
```
=> RIA-1603 adding addendum

e2e/features/case-list.feature, e2e/features/case-progression.feature, e2e/features/create-case-summary.feature, e2e/features/generate-decisions-and-reasons.feature, e2e/features/generate-hearing-bundle.feature, e2e/features/list-case.feature, e2e/features/send-decision-and-reasons.feature, e2e/features/start-decisions-and-reasons.feature, e2e/flows/list-case.flow.ts
[RIA-1571](https://tools.hmcts.net/jira/browse/RIA-1571)
based on branch RIA-1568
aria reference + list case by admin
```
[ ] Yes
[x] No
```
=> Ria 1571 list case from admin role

e2e/features/admin-feature-exposure.feature
=> Ria 1627 view tabs for admin user

e2e/features/case-progression.feature
[RIA-1560](https://tools.hmcts.net/jira/browse/RIA-1560)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1560 listing legal rep

Jenkinsfile_nightly, e2e/features.conf.js, e2e/features/submit-case.feature, e2e/ia.conf.js
=> Config changes for the nightly build failure

e2e/features/case-progression.feature, e2e/features/edit-case-listing.feature, e2e/features/list-case.feature, e2e/features/start-appeal.feature, e2e/flows/start-appeal.flow.ts
=> Ria 362 edit case listing

e2e/features/case-progression.feature, e2e/features/list-case.feature, e2e/flows/list-case.flow.ts
[RIA-1284](https://tools.hmcts.net/jira/browse/RIA-1284)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1284 prepare for hearing

e2e/features/case-progression.feature, e2e/features/list-case.feature
[RIA-1609](https://tools.hmcts.net/jira/browse/RIA-1609)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1609 prepare for hearing

e2e/features/end-appeal.feature, e2e/pages/any.page.ts
[RIA-823](https://tools.hmcts.net/jira/browse/RIA-823)
end appeal
```
[ ] Yes
[x] No
```
=> RIA-823 end appeal test

e2e/features/case-progression.feature, e2e/features/record-application.feature, e2e/features/stepDefinitions/ccd-form-page.steps.ts, e2e/pages/ccd-form.page.ts
[RIA-1485](https://tools.hmcts.net/jira/browse/RIA-1485)
record application
```
[ ] Yes
[x] No
```
=> Ria 1485 record application

e2e/features/case-progression.feature, e2e/features/record-hearing-attendees-and-duration.feature
=> Ria 572 hearing attendees and duration

e2e/features/case-progression.feature
[RIA-1622](https://tools.hmcts.net/jira/browse/RIA-1622)
overview pages
```
[ ] Yes
[x] No
```
=> Ria 1622 overview pages decided

Jenkinsfile_nightly
Fixing issues with deprecated features in the pipeline and also adding the new admin user to Jenkins secrets.
```
[ ] Yes
[x] No
```
=> fixing pipeline deprecation and adding an Admin user to Jenkins secrets

e2e/flows/start-appeal.flow.ts
[RIA-1762](https://tools.hmcts.net/jira/browse/RIA-1762)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-1762 add missing postcodes

e2e/features/record-application.feature
[RIA-1562](https://tools.hmcts.net/jira/browse/RIA-1562)
Launch and appeal from application request
```
[ ] Yes
[x] No
```
=> RIA-1562 launch end appeal from application request

e2e/features/case-progression.feature
https://tools.hmcts.net/jira/browse/RIA-1563
Tests to verify presence of progress bar in overview tab for legal rep when case is in pre-hearing state.
```
[ ] Yes
[x] No
```
=> Ria 1563 legrep prehearing progress

e2e/features/case-progression.feature
https://tools.hmcts.net/jira/browse/RIA-1565
Test to cover legar-rep overview page to have progress bar when the case is in final-bundling state.
```
[ ] Yes
[x] No
```
=> Ria 1565 legalrep finalbundle overview

e2e/features/case-progression.feature
https://tools.hmcts.net/jira/browse/RIA-1564
Tests to cover legal rep progress bar on overview page when the case is in decision state.
```
[ ] Yes
[x] No
```
=> Ria 1564 legalrep decision overview

README.md, e2e/features/case-list.feature, e2e/features/edit-case-listing.feature, e2e/features/list-case.feature, e2e/flows/start-appeal.flow.ts
[RIA-1380](https://tools.hmcts.net/jira/browse/RIA-1380)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1380 add hearing centres

e2e/features/end-appeal.feature, e2e/features/stepDefinitions/service/overview.steps.ts
[RIA-1677](https://tools.hmcts.net/jira/browse/RIA-1677)
Ended appeal overview tab view as case officer
```
[ ] Yes
[ x] No
```
=> RIA-1677 Overview tab: Ended appeal (Case Officer)

e2e/features/end-appeal.feature
[RIA-1678](https://tools.hmcts.net/jira/browse/RIA-1678)
Ended appeal overview tab view as legalrep
```
[ ] Yes
[ X] No
```
=> RIA-1678 Overview tab: Ended appeal (Legal Rep)

e2e/features/edit-case-listing.feature, e2e/features/record-application.feature
[RIA-1654](https://tools.hmcts.net/jira/browse/RIA-1654)
admin edit listing
```
[ ] Yes
[x] No
```
=> Ria 1654 admin edit case

Jenkinsfile_nightly, README.md, bin/create-users.sh, e2e/features/idam-sign-in.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/flows/authentication.flow.ts, e2e/ia.conf.js
[RIA-1304](https://tools.hmcts.net/jira/browse/RIA-1304)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1304 authenticate home office user

e2e/features/case-progression.feature, e2e/features/home-office-users-view-all-tabs.feature
[RIA-1356](https://tools.hmcts.net/jira/browse/RIA-1356)
Home office users tabs view
```
[ ] Yes
[x] No
```
=> RIA-1356 Home office users view tabs

e2e/features/stepDefinitions/service/respondent-evidence.steps.ts, e2e/features/upload-home-office-bundle.feature, e2e/flows/upload-respondent-evidence.flow.ts
https://tools.hmcts.net/jira/browse/RIA-1308
E2E tests to cover Home Office bundle upload by appropriate Home Office users.
```
[ ] Yes
[x] No
```
=> Ria 1308 Home Office bundle upload

e2e/features/case-progression.feature, e2e/features/home-office-exposure.feature, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/flows/upload-respondent-evidence.flow.ts
[RIA-1707](https://tools.hmcts.net/jira/browse/RIA-1707)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1707 awaiting ho evidence

e2e/features/home-office-exposure.feature, e2e/pages/any.page.ts
[RIA-1798](https://tools.hmcts.net/jira/browse/RIA-1798)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1798 ho evidence uploaded

e2e/features/case-progression.feature, e2e/features/request-case-building.feature
[RIA-1789](https://tools.hmcts.net/jira/browse/RIA-1789)
Request case building direction to legal representative.
```
[ ] Yes
[x] No
```
=> Ria 1789 request case building direction to legal rep

e2e/features/case-progression.feature, e2e/features/home-office-exposure.feature
[RIA-1357](https://tools.hmcts.net/jira/browse/RIA-1357)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1357 case building ho users

e2e/features/upload-home-office-appeal-response.feature
https://tools.hmcts.net/jira/browse/RIA-1309
Upload appeal response by Home Office
```
[ ] Yes
[X] No
```
=> Ria 1309 upload ho appeal response

e2e/features/case-progression.feature, e2e/features/upload-home-office-appeal-response.feature
[RIA-1803](https://tools.hmcts.net/jira/browse/RIA-1803)
post upload response appeal overview tab
```
[ ] Yes
[x] No
```
=> RIA-1803 post upload appeal response overview tab

e2e/features/case-progression.feature, e2e/features/home-office-all-overview-tabs.feature, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/upload-home-office-appeal-response.feature
https://tools.hmcts.net/jira/browse/RIA-1709
Overview tabs from Listing to Decided state for all Home Office users.
```
[ ] Yes
[x] No
```
=> Ria 1709 ho all overview tabs

e2e/features/case-progression.feature, e2e/features/home-office-response-amend.feature, e2e/features/home-office-response-review.feature
[RIA-1794](https://tools.hmcts.net/jira/browse/RIA-1794)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1794 ho response under review

e2e/features/add-addendum-evidence.feature, e2e/features/case-progression.feature, e2e/features/generate-decisions-and-reasons.feature, e2e/features/stepDefinitions/service/case-details-page.steps.ts
[RIA-2037](https://tools.hmcts.net/jira/browse/RIA-2037)
Ho as a user decision case fields should not be displayed
```
[ ] Yes
[x] No
```
=> RIA-2037 ho as a user decision fields should not be displayed

e2e/features/case-progression.feature, e2e/flows/start-appeal.flow.ts, e2e/pages/any.page.ts
[RIA-1277](https://tools.hmcts.net/jira/browse/RIA-1277)
New fields added to appeal submission form
```
[ ] Yes
[x] No
```
=> RIA-1277 new fields to appeal submission form

e2e/features/case-progression.feature, e2e/features/home-office-users-view-all-tabs.feature, e2e/features/stepDefinitions/service/appeal.steps.ts, e2e/features/stepDefinitions/service/appellant.steps.ts, e2e/features/stepDefinitions/service/case-details-page.steps.ts, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-appeal-new-appellant-tab.feature, e2e/features/submit-appeal.feature, e2e/flows/start-appeal.flow.ts
[RIA-1771](https://tools.hmcts.net/jira/browse/RIA-1771)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1771 appeal and appellant tabs

e2e/features/build-case.feature, e2e/features/generate-decisions-and-reasons.feature, e2e/features/home-office-exposure.feature, e2e/features/list-case.feature, e2e/features/send-decision-and-reasons.feature, e2e/features/start-decisions-and-reasons.feature
=> Removed/added nightly_test tag

e2e/features/list-case.feature
=> Added nightly tag

e2e/features/add-addendum-evidence-legal-rep.feature, e2e/features/case-progression.feature
[RIA-1845](https://tools.hmcts.net/jira/browse/RIA-1845)
add addendum evidences by Legal Rep
```
[ ] Yes
[x] No
```
=> RIA-1845 add addendum evidences by Legal Rep

e2e/features/add-appeal-response.feature, e2e/features/case-progression.feature, e2e/features/upload-home-office-appeal-response.feature
https://tools.hmcts.net/jira/browse/RIA-2177
Changes to list uploaded HO appeal response and ability to only add documents without deleting/replacing any
```
[ ] Yes
[X] No
```
=> Ria 2177 list ho appeal response

e2e/features/case-list.feature, e2e/features/edit-case-listing.feature, e2e/features/list-case.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/start-appeal.flow.ts
[RIA-1976](https://tools.hmcts.net/jira/browse/RIA-1976)
add new hearing centres
```
[ ] Yes
[x] No
```
=> RIA-1976 add new hearing centres

e2e/features/add-addendum-evidence.feature, e2e/features/case-progression.feature, e2e/features/create-case-summary.feature, e2e/features/create-user.feature, e2e/features/edit-case-listing.feature, e2e/features/end-appeal.feature, e2e/features/generate-decisions-and-reasons.feature, e2e/features/generate-hearing-bundle.feature, e2e/features/home-office-all-overview-tabs.feature, e2e/features/home-office-exposure.feature, e2e/features/home-office-users-view-all-tabs.feature, e2e/features/record-application.feature, e2e/features/record-hearing-attendees-and-duration.feature, e2e/features/send-decision-and-reasons.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/stepDefinitions/service/submit-hearing-requirments.steps.ts, e2e/features/submit-hearing-requirements.feature, e2e/flows/submit-hearing-requirements.flow.ts
[RIA-436](https://tools.hmcts.net/jira/browse/RIA-436)
[RIA-2087](https://tools.hmcts.net/jira/browse/RIA-2087)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-436-2087 submit hearing requirements

e2e/features/case-progression.feature, e2e/features/request-hearing-requirements.feature
https://tools.hmcts.net/jira/browse/RIA-1784
CO and Admin Officer overview tabs for submitHearingRequirements state
```
[ ] Yes
[X] No
```
=> Ria 1784 submit hearing overview

e2e/features/case-progression.feature, e2e/features/home-office-response-review.feature
[RIA-1946](https://tools.hmcts.net/jira/browse/RIA-1946)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-1946 ho response review

e2e/features/case-progression.feature, e2e/features/submit-hearing-requirements.feature
[RIA-2049](https://tools.hmcts.net/jira/browse/RIA-2049)
Legal rep overview tab for submit hearing requirements
```
[ ] Yes
[x] No
```
=> RIA-2049 overview tab submit hearing requirements

e2e/features/remove-appeal-from-the-online-service.feature, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/stepDefinitions/service/remove-appeal.steps.ts, e2e/flows/remove-appeal.flow.ts
[RIA-1147](https://tools.hmcts.net/jira/browse/RIA-1147)
Exit appeal from the online service
```
[ ] Yes
[x] No
```
=> RIA-1147 exit appeal from online service

bin/create-users.sh
https://tools.hmcts.net/jira/browse/RIA-1955
Added a citizen user account used for testing
```
[ ] Yes
[x ] No
```
=> RIA-1955: Added a citizen user account used for testing

e2e/features/case-progression.feature, e2e/features/stepDefinitions/service/submit-hearing-requirments.steps.ts, e2e/features/submit-hearing-requirements.feature
https://tools.hmcts.net/jira/browse/RIA-1899
Tests to cover new Hearing tab
```
[ ] Yes
[X] No
```
=> Ria 1899 hearing tab

e2e/features/stepDefinitions/service/overview.steps.ts
N/A
fix Home Office ref number cut
```
[ ] Yes
[x] No
```
=> fix Home Office ref number cut

e2e/features/case-progression.feature, e2e/features/submit-hearing-requirements.feature
[RIA-2047](https://tools.hmcts.net/jira/browse/RIA-2047)
Direction to legal rep to submit hearing requirements
```
[ ] Yes
[x] No
```
=> RIA-2047 direction submit hearing requirements

e2e/features/case-progression.feature, e2e/features/create-user.feature, e2e/features/record-agreed-hearing-requirements.feature, e2e/features/stepDefinitions/service/adjust-hearing-requirments.steps.ts, e2e/features/stepDefinitions/service/submit-hearing-requirments.steps.ts, e2e/features/submit-hearing-requirements.feature, e2e/flows/submit-hearing-requirements-no-path.flow.ts, e2e/flows/submit-hearing-requirements-yes-path.flow.ts
RIA-587, RIA-2022, RIA-2168, RIA-2048, RIA-2051
complete feature hearing requirements
```
[ ] Yes
[x] No
```
=> Hearing requirements

e2e/features/admin-feature-exposure.feature, e2e/features/case-progression.feature, e2e/features/change-direction-due-date.feature, e2e/features/end-appeal.feature, e2e/features/home-office-exposure.feature, e2e/features/home-office-response-amend.feature, e2e/features/home-office-response-review.feature, e2e/features/stepDefinitions/service/appellant.steps.ts, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/submit-appeal-new-appellant-tab.feature, e2e/features/submit-hearing-requirements.feature, e2e/fields/complex-field-finders/table-collection-finder.ts
[RIA-723](https://tools.hmcts.net/jira/browse/RIA-723)
change direction date
```
[ ] Yes
[x] No
```
=> RIA-723 change direction date

e2e/features/case-progression.feature, e2e/features/list-case-after-submit-hearing-requirements.feature
https://tools.hmcts.net/jira/browse/RIA-2011
modify admin listing to remove hearing requirements page
```
[ ] Yes
[X] No
```
=> Ria 2011 modify admin listing

e2e/features/add-addendum-evidence-ho.feature, e2e/features/add-addendum-evidence-legal-rep.feature, e2e/features/add-addendum-evidence.feature, e2e/features/admin-feature-exposure.feature, e2e/features/case-progression.feature, e2e/features/create-case-summary.feature, e2e/features/create-user.feature, e2e/features/edit-case-listing.feature, e2e/features/end-appeal.feature, e2e/features/generate-decisions-and-reasons.feature, e2e/features/generate-hearing-bundle.feature, e2e/features/hearing-details-in-hearing-tab.feature, e2e/features/home-office-all-overview-tabs.feature, e2e/features/home-office-exposure.feature, e2e/features/home-office-users-view-all-tabs.feature, e2e/features/list-case.feature, e2e/features/record-agreed-hearing-requirements.feature, e2e/features/record-application.feature, e2e/features/record-hearing-attendees-and-duration.feature, e2e/features/send-decision-and-reasons.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/stepDefinitions/service/respondent-response.steps.ts, e2e/features/stepDefinitions/service/submit-hearing-requirments.steps.ts, e2e/features/submit-hearing-requirements.feature, e2e/flows/request-respondent-review.flow.ts
https://tools.hmcts.net/jira/browse/RIA-2052
Hearing details under hearing tab
```
[ ] Yes
[X] No
```
=> Ria 2052 hearing details under hearing tab

e2e/features/case-progression.feature, e2e/features/record-agreed-hearing-requirements.feature
[RIA-2277](https://tools.hmcts.net/jira/browse/RIA-2277)
Case officer overview tab at pre-listing
```
[ ] Yes
[x] No
```
=> RIA-2277 case officer overview tab pre-listing

e2e/features/case-progression.feature, e2e/features/list-case-after-submit-hearing-requirements.feature
https://tools.hmcts.net/jira/browse/RIA-2343
Admin Officer overview tab for hearing requirements flow
```
[ ] Yes
[X] No
```
=> RIA-2343: tests to cover Admin Officer overview tab for hearing requirements flow

e2e/features/case-progression.feature, e2e/features/submit-hearing-requirements.feature
[RIA-2304](https://tools.hmcts.net/jira/browse/RIA-2304)
dates to avoid on one screen
```
[ ] Yes
[x] No
```
=> RIA-2304 dates to avoid on one screen

e2e/features/case-progression.feature, e2e/features/list-case-without-hearing-requirements.feature
https://tools.hmcts.net/jira/browse/RIA-2041
List case without Hearing requirements
```
[ ] Yes
[X] No
```
=> Ria 2041 list without hearing reqmts

e2e/features/add-addendum-evidence.feature, e2e/features/case-progression.feature, e2e/features/create-case-summary.feature, e2e/features/edit-case-listing.feature, e2e/features/end-appeal.feature, e2e/features/generate-decisions-and-reasons.feature, e2e/features/generate-hearing-bundle.feature, e2e/features/home-office-all-overview-tabs.feature, e2e/features/home-office-exposure.feature, e2e/features/home-office-users-view-all-tabs.feature, e2e/features/list-case.feature, e2e/features/record-application.feature, e2e/features/record-hearing-attendees-and-duration.feature, e2e/features/send-decision-and-reasons.feature, e2e/features/start-decisions-and-reasons.feature, e2e/flows/list-case.flow.ts
N/A
fix e2e tests for new features
```
[ ] Yes
[x] No
```
=> fix e2e tests for new features

e2e/features/case-list.feature, e2e/features/case-search.feature
https://tools.hmcts.net/jira/browse/RIA-1478
Modify search results columns
```
[ ] Yes
[X] No
```
=> Ria 1478 search result fields

e2e/features/case-list.feature, e2e/features/case-search.feature, e2e/features/stepDefinitions/service/case-list-page.steps.ts, e2e/flows/case-list.flow.ts
https://tools.hmcts.net/jira/browse/RIA-1465
Updated case list and search filter criteria
```
[ ] Yes
[X] No
```
=> Ria 1465 search filters

e2e/features/record-application.feature
[RIA-1891](https://tools.hmcts.net/jira/browse/RIA-1891)
mark application completed after ending appeal
```
[ ] Yes
[ ] No
```
=> RIA-1891 mark application completed after ending appeal

e2e/pages/ccd.page.ts, package.json
N/A
nightly build fix
```
[ ] Yes
[x] No
```
=> nightly build fix

e2e/features/case-progression.feature, e2e/features/record-application.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/features/stepDefinitions/ccd-page.steps.ts
[RIA-1500](https://tools.hmcts.net/jira/browse/RIA-1500)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-1500 extend due date from application request

e2e/features/remove-appeal-from-the-online-service.feature
Fix for RIA-1500.
[RIA-1500](https://tools.hmcts.net/jira/browse/RIA-1500)
_Record an application_ link removed from Applications tab for the **removeAppealFromOnline** event.
```
[ ] Yes
[x] No
```
=> RIA-1550 fix record an application link

README.md, e2e/aip/ccd-service.ts, e2e/aip/idam-service.ts, e2e/aip/s2s.ts, e2e/features/appellant-request-reasons-for-appeal.feature, e2e/features/stepDefinitions/service/appelant-submit-case.steps.ts, e2e/ia.conf.js, package.json, yarn.lock
Added setup to create a appellant case via the CCD api. Then test that
the TCW can request the appellant to enter their reasons for appeal.
https://tools.hmcts.net/jira/browse/RIA-2493
=> RIA-2493 TCW can request reasons for appeal from appellant

Jenkinsfile_nightly, e2e/ia.conf.js
aat web url change to xui
```
[ ] Yes
[X] No
```
=> night-test aat gateway url

e2e/features/edit-case-listing-after-update-hearing-adjustments.feature, e2e/features/stepDefinitions/service/agreed-hearing-requirments.steps.ts, e2e/features/stepDefinitions/service/list-case.steps.ts, e2e/flows/list-case.flow.ts, e2e/flows/record-agreed-requirements.flow.ts, e2e/flows/submit-hearing-requirements.flow.ts
https://tools.hmcts.net/jira/browse/RIA-2398
Changes to relisting case after review update hearing requirements
```
[ ] Yes
[X] No
```
=> Ria 2398 ao list case

e2e/features/case-progression-admin.feature, e2e/features/case-progression-judge.feature, e2e/features/case-progression.feature, e2e/features/end-appeal.feature, e2e/features/home-office-response-review.feature, e2e/features/idam-sign-in.feature, e2e/features/remove-appeal-from-the-online-service.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/flows/authentication.flow.ts, e2e/ia.conf.js
[RIA-1360](https://tools.hmcts.net/jira/browse/RIA-1360)
Judge user login
```
[ ] Yes
[x] No
```
=> RIA-1360 Judge user login

e2e/features/case-progression.feature, e2e/features/journey-type-tag.feature, e2e/features/stepDefinitions/service/overview.steps.ts
https://tools.hmcts.net/jira/browse/RIA-2610
=> RIA-2610 Added tests for the journey type flag shown on the overview page.

e2e/features/edit-case-listing-after-update-hearing-adjustments.feature, e2e/features/send-case-preHearing-bundle-failed.feature
https://tools.hmcts.net/jira/browse/RIA-2723
New event - Send to preHearing state
```
[ ] Yes
[ X] No
```
=> RIA-2723 New event - Send to preHearing state

e2e/features/case-progression-admin.feature, e2e/features/case-progression-judge.feature, e2e/features/case-progression.feature, e2e/features/create-user.feature, e2e/features/home-office-all-overview-tabs.feature, e2e/features/home-office-exposure.feature, e2e/features/home-office-users-view-all-tabs.feature, e2e/features/prepare-decisions-and-reasons.feature, e2e/features/record-hearing-attendees-and-duration.feature, e2e/features/send-decision-and-reasons.feature, e2e/features/stepDefinitions/service/generate-decision-and-reasons.steps.ts, e2e/features/stepDefinitions/service/prepare-decision-and-reasons.steps.ts, e2e/flows/prepare-decision-and-reasons.flow.ts
https://tools.hmcts.net/jira/browse/RIA-1280
Prepare Decision and Reasons document by Judge
```
[ ] Yes
[X] No
```
=> Ria 1280 judge generate decisions

e2e/features/end-appeal.feature
[RIA-2239](https://tools.hmcts.net/jira/browse/RIA-2239)
Changed end-appeal feature to add judge user 
```
[ ] Yes
[X] No
```
=> Ria 2239 judge end appeal

e2e/features/case-progression-admin.feature, e2e/features/case-progression-judge.feature, e2e/features/case-progression.feature, e2e/flows/send-decision-and-reasons.flow.ts
https://tools.hmcts.net/jira/browse/RIA-1939
Upload and send Decision and Reasons document (FT Judge)
```
[ ] Yes
[X] No
```
=> Ria 1939 judge upload decision

e2e/features/record-grant-update-hearing-requirements.feature
https://tools.hmcts.net/jira/browse/RIA-2634
Added a cucumber feature test to test out the granting of a change of hearing centre application.
```
[ ] Yes
[x] No
```
=> RIA-2634: Change of designated hearing centre

e2e/features/submit-change-hearing-centre.feature
https://tools.hmcts.net/jira/browse/RIA-2558
Added a feature test for the `change hearing office` event.
```
[ ] Yes
[x] No
```
=> RIA-2558: Change designated hearing centre

e2e/features/edit-documents.feature
https://tools.hmcts.net/jira/browse/RIA-2913
=> RIA-2913 first simple step for now

e2e/aip/ccd-service.ts, e2e/features/appellant-submits-reasons-for-appeal.feature, e2e/features/journey-type-tag.feature, e2e/features/stepDefinitions/service/appelant-submit-case.steps.ts
Added test that checks the TCW can review the reasons for appeal and
send it on to the respondent.
https://tools.hmcts.net/jira/browse/RIA-2866
=> RIA-2866 TCW reviews reasons for appeal

e2e/features/ftpa-appellant-leadership-judge-decision-and-reasons.feature, e2e/features/ftpa-respondent-leadership-judge-decision-and-reasons.feature, e2e/features/stepDefinitions/service/ftpa-permission-to-appeal.steps.ts, e2e/flows/ftpa-appellant-appeal.flow.ts, e2e/flows/ftpa-respondent-appeal.ts
[RIA-2932](https://tools.hmcts.net/jira/browse/RIA-2932)
Ftpa documents should be visible to other parties in granted and partially granted outcomes
```
[ ] Yes
[x] No
```
=> RIA-2932 ftpa documents visible to the other party

e2e/features/ftpa-appellant.feature, e2e/features/ftpa-respondent.feature
N/A
fix admin ftpa overview page tests
```
[ ] Yes
[x] No
```
=> fix admin ftpa overview page tests

e2e/features/ftpa-appellant-leadership-judge-decision-and-reasons.feature, e2e/features/ftpa-appellant.feature, e2e/features/ftpa-respondent-leadership-judge-decision-and-reasons.feature, e2e/features/ftpa-respondent.feature, e2e/features/stepDefinitions/service/ftpa-appeal.steps.ts
https://tools.hmcts.net/jira/browse/RIA-2564
tests to cover Overview tabs for all users after leadership judge decision is made
```
[ ] Yes
[X] No
```
=> Ria 2564 leadership judge decision overview tabs

e2e/aip/ccd-service.ts, e2e/features/appellant-submits-reasons-for-appeal.feature, e2e/features/journey-type-tag.feature, e2e/features/stepDefinitions/service/appelant-submit-case.steps.ts, e2e/features/stepDefinitions/service/appelant-submit-time-extension.steps.ts, e2e/features/time-extension.feature
Allow TCW to review time extrensions
RIA-2832
=> Ria 2832 time extensions

e2e/features/edit-appeal.feature, e2e/features/overview-tab.feature, e2e/features/start-appeal-alternate-paths.feature, e2e/features/start-appeal-confirmation.feature, e2e/features/start-appeal-grounds-of-appeal.feature, e2e/features/start-appeal-manual-address.feature, e2e/features/start-appeal-other-appeal-validation.feature, e2e/features/start-appeal.feature, e2e/features/stepDefinitions/service/appeal.steps.ts, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/start-appeal.flow.ts
[RIA-2733](https://tools.hmcts.net/jira/browse/RIA-2733)
```
[ ] Yes
[x] No
```
=> RIA-2733 update appeal submission journey

e2e/features/start-appeal-grounds-of-appeal.feature
[RIA-2693](https://github.com/hmcts/ia-case-documents-api/pull/211)
New appeal submission template
```
[ ] Yes
[x] No
```
=> RIA-2693 new submit appeal template

e2e/features/start-appeal-screening-questions.feature, e2e/flows/start-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3078
=> RIA-3078 remove checklist option

e2e/features/flag-case.feature, e2e/features/stepDefinitions/service/overview.steps.ts
https://tools.hmcts.net/jira/browse/RIA-1742
- Testing single flags with additional details
- Testing multiple flags with additional details
- Testing multiple flags with some additional details
- Updated `overview.steps.ts` to let test for `caseFlag` images.
```
[ ] Yes
[x] No
```
=> RIA-1742: Adding a case flag feature test.

e2e/features/clarifying-questions-extension.feature, e2e/features/time-extension.feature
Test for TCW raising clarifying questions
https://tools.hmcts.net/jira/browse/RIA-2864
=> RIA-2864 Clarifying question

e2e/features/flag-case.feature
https://tools.hmcts.net/jira/browse/RIA-2513
- E2E test added to the existing flag case feature.
```
[ ] Yes
[x] No
```
=> RIA-2513: Removing flags

e2e/aip/ccd-service.ts, e2e/features/clarifying-questions-extension.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/stepDefinitions/service/appelant-submit-clarifying-questions.steps.ts, e2e/pages/any.page.ts
TCW can view clarifying answers on the appeal page.
https://tools.hmcts.net/jira/browse/RIA-2301
```
[ ] Yes
[X] No
```
=> RIA-2301-View clarifying answers

e2e/features/add-appeal-response.feature, e2e/features/case-progression.feature, e2e/features/home-office-users-view-all-tabs.feature, e2e/features/request-case-building.feature, e2e/features/request-hearing-requirements.feature, e2e/features/request-respondent-evidence.feature, e2e/features/request-respondent-review.feature, e2e/features/upload-respondent-evidence.feature
[RIA-2694](https://tools.hmcts.net/jira/browse/RIA-2694)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-2694 generic directions and notifications

e2e/features/case-management-appointment.feature
TCW requests CMA requirements
https://tools.hmcts.net/jira/browse/RIA-3017
```
[ ] Yes
[X] No
```
=> RIA-3017 TCW requests CMA requirements

e2e/cucumber.conf.js, e2e/features/case-list.feature, e2e/features/case-selection.feature, e2e/features/stepDefinitions/service/case-list-page.steps.ts
https://tools.hmcts.net/jira/browse/RIA-3260
=> RIA-3260 rename case type

e2e/features/start-appeal-grounds-of-appeal.feature
[RIA-3246](https://tools.hmcts.net/jira/browse/RIA-3246)
```
[ ] Yes
[x] No
```
=> RIA-3246 change appeal-type description

e2e/features/force-case-progression-to-submit-hearing-requirements.feature
https://tools.hmcts.net/jira/browse/RIA-2776
- Added a new feature test for the event.
```
[ ] Yes
[x] No
```
=> RIA-2776: Force case progression to submit hearing requirements.

e2e/features/update-legal-representatives-details.feature
https://tools.hmcts.net/jira/browse/RIA-1358
Added update legal representatives details event e2e test.
```
[ ] Yes
[x] No
```
=> RIA-1358: Update legal representative's details

e2e/features/adjourn-without-a-date.feature
=> ria 2970 adjourn

e2e/features/adjourn-without-a-date.feature, e2e/features/relist-an-adjourned-case.feature
* add adjourn without a date test
* remove tag
* added coverage for the hearing notice document
* remove 2970 check
```
[ ] Yes
[ ] No
```
=> Feature/ria 2957 add adjourn event (#239)

e2e/features/adjourn-without-a-date.feature, e2e/features/decision-without-hearing.feature
https://tools.hmcts.net/jira/browse/RIA-2122
Decision without hearing
```
[ ] Yes
[x] No
```
=> Ria 2122 decision without hearing

e2e/features/start-appeal-home-office-reference.feature
[RIA-3389](https://tools.hmcts.net/jira/browse/RIA-3389)
```
[x] Yes
[ ] No
```
=> RIA-3389 Accept non-standard HO refs

e2e/features/adjourn-without-a-date.feature, e2e/features/case-progression.feature, e2e/features/edit-case-listing.feature, e2e/features/hearing-details-in-hearing-tab.feature, e2e/features/list-case-after-agreed-hearing-requirements.feature, e2e/features/list-case-without-hearing-requirements.feature, e2e/features/list-case.feature, e2e/features/record-agreed-hearing-requirements.feature, e2e/features/record-application.feature, e2e/features/relist-an-adjourned-case.feature, e2e/features/stepDefinitions/service/agreed-hearing-requirments.steps.ts, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/update-hearing-adjustments.feature, e2e/flows/list-case.flow.ts, e2e/flows/record-agreed-requirements.flow.ts
Updating field names after change
```
[ ] Yes
[x ] No
```
=> Updating field names

e2e/features/case-progression.feature, e2e/features/ftpa-respondent-leadership-judge-decision-and-reasons.feature, e2e/features/hearing-details-in-hearing-tab.feature, e2e/features/list-case-after-agreed-hearing-requirements.feature, e2e/features/list-case-after-submit-hearing-requirements-validation.feature, e2e/features/list-case-without-hearing-requirements.feature, e2e/features/record-agreed-hearing-requirements.feature, e2e/features/record-hearing-attendees-and-duration.feature, e2e/features/submit-hearing-requirements.feature, e2e/features/update-hearing-adjustments.feature, e2e/features/update-hearing-requirements.feature
Updating tab name from Hearing to Hearing and appointment
```
[ ] Yes
[ x] No
```
=> Tab name update

e2e/features/edit-appeal.feature
https://tools.hmcts.net/jira/browse/RIA-1359
- The RIA-653 `edit-appeal` test was  broken, so fixed the breaks.
- For RIA-1359 test, this is taking it through the whole journey of creating a record, then going through the editing of appeal.
```
[ ] Yes
[x] No
```
=> RIA-1359: Edit appeal after submit event end to end test added.

e2e/features/link-appeal.feature
https://tools.hmcts.net/jira/browse/RIA-3291
=> RIA-3291 add link and unlink e2e tests

e2e/features/record-agreed-hearing-requirements.feature, e2e/features/stepDefinitions/service/agreed-hearing-requirments.steps.ts, e2e/flows/list-case.flow.ts, e2e/flows/record-agreed-requirements.flow.ts
=> RIA-3255-fixed tests

e2e/features/case-progression-save-and-continue-true.feature, e2e/features/end-appeal.feature
https://tools.hmcts.net/jira/browse/RIA-2717
Added exit survey link to appealEnded and decided states
```
[ ] Yes
[X] No
```
=> RIA-2717: Added exit survey to appealEnded and decided states

e2e/features/force-case-progression.feature
https://tools.hmcts.net/jira/browse/RIA-2774
=> RIA-2774 add e2e test

e2e/features/ftpa-appellant-leadership-judge-decision-and-reasons.feature, e2e/features/ftpa-respondent-leadership-judge-decision-and-reasons.feature
https://tools.hmcts.net/jira/browse/RIA-3393
Fixed overview tabs in ftpa decided state
```
[ ] Yes
[X] No
```
=> RIA-3393: Fixed overview tabs in ftpa decided state

e2e/features/ftpa-appellant-resident-judge-decision-and-reasons.feature, e2e/features/ftpa-respondent-resident-judge-decision-and-reasons.feature
https://tools.hmcts.net/jira/browse/RIA-2571
tests for resident judge decision overview tabs
```
[ ] Yes
[X] No
```
=> Ria 2571 resident judge decision overview tabs

e2e/features/ftpa-appellant-leadership-judge-decision-and-reasons.feature, e2e/features/ftpa-appellant-resident-judge-decision-and-reasons.feature, e2e/features/ftpa-respondent-leadership-judge-decision-and-reasons.feature, e2e/features/ftpa-respondent-resident-judge-decision-and-reasons.feature
[RIA-2971](https://tools.hmcts.net/jira/browse/RIA-2971)
Ftpa tribunal notes in granted/partiall-granted outcomes is visible to only CO, Admin and Judge
```
[ ] Yes
[x] No
```
=> RIA-2971 ftpa tribunal notes visible to only tribunal users

e2e/features/ftpa-appellant-leadership-judge-decision-and-reasons.feature, e2e/features/ftpa-appellant-resident-judge-decision-and-reasons.feature, e2e/features/ftpa-respondent-leadership-judge-decision-and-reasons.feature, e2e/features/ftpa-respondent-resident-judge-decision-and-reasons.feature, e2e/flows/ftpa-appellant-appeal.flow.ts, e2e/flows/ftpa-respondent-appeal.ts
https://tools.hmcts.net/jira/browse/RIA-3211
Aggregated flags to manage the event pages in ftpa decided state
```
[ ] Yes
[X] No
```
=> Ria 3211 rj ftpa decided

e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/ftpa-display-final-decision-scenario-10.feature, e2e/features/ftpa-display-final-decision-scenario-11.feature, e2e/features/ftpa-display-final-decision-scenario-12.feature, e2e/features/ftpa-display-final-decision-scenario-13.feature, e2e/features/ftpa-display-final-decision-scenario-14.feature, e2e/features/ftpa-display-final-decision-scenario-2.feature, e2e/features/ftpa-display-final-decision-scenario-3.feature, e2e/features/ftpa-display-final-decision-scenario-4.feature, e2e/features/ftpa-display-final-decision-scenario-5.feature, e2e/features/ftpa-display-final-decision-scenario-6.feature, e2e/features/ftpa-display-final-decision-scenario-7.feature, e2e/features/ftpa-display-final-decision-scenario-8.feature, e2e/features/ftpa-display-final-decision-scenario-9.feature, e2e/features/stepDefinitions/service/send-decision-and-reasons.steps.ts, e2e/flows/send-decision-and-reasons.flow.ts
[RIA-2919](https://tools.hmcts.net/jira/browse/RIA-2919)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 2919 final decision for two applications

e2e/features/appeal-tab.feature, e2e/features/case-progression-save-and-continue-false.feature, e2e/features/case-progression-save-and-continue-true.feature, e2e/features/edit-appeal.feature, e2e/features/home-office-users-view-all-tabs.feature, e2e/features/start-appeal.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/start-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3334
=> RIA-3334 update appeal tab test to include deportation order screen

e2e/features/share-a-case.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/features/stepDefinitions/service/share-a-case.steps.ts, e2e/flows/authentication.flow.ts, e2e/ia.conf.js
This change incorporates adding a basic happy path
testing for share-a-case feature.
Files added/changed:
e2e/features/share-a-case.feature
e2e/features/stepDefinitions/authentication.steps.ts
e2e/features/stepDefinitions/service/share-a-case.steps.ts
e2e/flows/authentication.flow.ts
e2e/ia.conf.js
https://tools.hmcts.net/jira/browse/RIA-3536
```
- [] Yes
```
=> RIA-3536: Basic ptor test for share-a-case-feature.

e2e/features/appeal-payment-failed.feature, e2e/features/ea-hu-appeal-pay-later.feature
[RIA-3082](https://tools.hmcts.net/jira/browse/RIA-3082)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-3082 submit appeal failed payment

e2e/features/appeal-submitted-ho-overview.feature, e2e/features/appeal-submitted-state-visibility-to-ho.feature
[RIA-3340](https://tools.hmcts.net/jira/browse/RIA-3340)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3340 appeal submitted visibility for ho users

e2e/features/ea-hu-appeal-pay-later.feature
[RIA-3469](https://tools.hmcts.net/jira/browse/RIA-3469)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-3469 EA HU appeal pay later

e2e/features/payment-history-tab.feature
[RIA-3057](https://tools.hmcts.net/jira/browse/RIA-3057)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3057 payment history tab

e2e/features/submit-appeal.feature
Home office validation tab for submit appeal
https://tools.hmcts.net/jira/browse/RIA-3271
Once the appeal is submitted, home office details are displayed in a new tab 'Validation' for case-officer
```
[ ] Yes
[ x] No
```
=> RIA-3271: Home office validation tab for submit appeal

e2e/features/pa-appeal-pay-now.feature
https://tools.hmcts.net/jira/browse/RIA-3498
RIA-3498_Error_Submit
```
[ ] Yes
[X] No
```
=> Ria 3498 error submit

e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-appeal-and-make-payment.feature, e2e/flows/start-appeal.flow.ts
[RIA-3163](https://tools.hmcts.net/jira/browse/RIA-3163)
Make a payment after submitting the appeal for EA/HU/PA appeal types
```
[ ] Yes
[x] No
```
=> RIA-3163 payment after submit appeal

bin/runTest.sh, e2e/features/add-addendum-evidence-admin-officer.feature, e2e/features/add-addendum-evidence-ho.feature, e2e/features/add-addendum-evidence.feature, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/stepDefinitions/service/send-case-pre-hearing.steps.ts, e2e/flows/send-case-pre-hearing.flow.ts, e2e/flows/submit-hearing-requirements.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3366
Added e2e test for admin officer addendum evidence
```
[ ] Yes
[ x] No
```
=> RIA-3366: UploadAddendumEvidence for Admin Officers

e2e/features/submit-appeal-and-make-payment.feature
https://tools.hmcts.net/jira/browse/RIA-3409
RIA-3409-AvoidPayTwice
```
[ ] Yes
[X] No
```
=> Ria 3409 avoid pay twice

e2e/features/pa-appeal-pay-later.feature
https://tools.hmcts.net/jira/browse/RIA-3415
RIA-3415_PA_PAY_LATER'
```
[ ] Yes
[X] No
```
=> RIA-3415_PA_Pay_Later

e2e/features/start-appeal-address-validation.feature, e2e/features/start-appeal-alternate-paths.feature, e2e/features/start-appeal-confirmation.feature, e2e/features/start-appeal-grounds-of-appeal.feature, e2e/features/start-appeal-manual-address.feature, e2e/features/start-appeal-nationalities.feature, e2e/features/start-appeal-other-appeal-validation.feature, e2e/features/start-appeal.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/start-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-2010
Add stateless
```
[ ] Yes
[N] No
```
=> Ria 2010 add stateless

e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/upload-sensitive-documents.feature
https://tools.hmcts.net/jira/browse/RIA-3392
=> RIA-3392 Delete sensitive documents

e2e/features/pay-offline-by-card.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/start-appeal.flow.ts
[RIA-3434](https://tools.hmcts.net/jira/browse/RIA-3434)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3434 pay offline by card pa

e2e/features/payment-pending-state-visible-to-tribunal.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-appeal-with-offline-payment.feature, e2e/flows/start-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3278
RIA-3278_State_Payment_Pending
```
[ ] Yes
[X] No
```
=> Ria 3278 state payment pending

e2e/features/adjourn-without-a-date.feature, e2e/features/relist-an-adjourned-case.feature
https://tools.hmcts.net/jira/browse/RIA-3347
=> update test for issue 1 fix

.gitignore, e2e/features/mark-appeal-as-paid.feature, e2e/fields/CcdWriteMoneyGBPField.ts, e2e/fields/CcdWriteMoneyGBPFieldFinder.ts, e2e/fields/fields.ts, e2e/flows/start-appeal.flow.ts
[RIA-3473](https://tools.hmcts.net/jira/browse/RIA-3473)
Mark appeal as paid for the appeal types EA/HU/PA
```
[ ] Yes
[x] No
```
=> RIA-3473 mark appeal as paid of appeal type PA

e2e/features/mark-appeal-as-paid-after-listing.feature
https://tools.hmcts.net/jira/browse/RIA-3219
add a feature for appeal paid after listing
```
[ ] Yes
[X ] No
```
=> Ria 3219 mark appeal as paid after listing

e2e/features/duplicate-payment-error-handling.feature, e2e/flows/start-appeal.flow.ts
[RIA-3574](https://tools.hmcts.net/jira/browse/RIA-3574)
Duplicate payments error handling
```
[ ] Yes
[x] No
```
=> RIA-3574 duplicate payment handling

e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-appeal-out-off-time-payment.feature, e2e/flows/start-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3471
RIA-3471_Out_Of_Time paid messages
```
[ ] Yes
[X] No
```
=> Ria 3471 out of time

e2e/features/upload-home-office-bundle.feature
[RIA-3591](https://tools.hmcts.net/jira/browse/RIA-3591)
```
[ ] Yes
[x] No
```
=> RIA-3591 Update document label in HO bundle

e2e/features/mark-appeal-as-paid.feature, e2e/features/pay-offline-by-card.feature, e2e/features/submit-appeal-and-make-payment.feature
https://tools.hmcts.net/jira/browse/RIA-3592
RIA-3592_payment_method and payment status
```
[ ] Yes
[X] No
```
=> Ria 3592 payment method

e2e/flows/start-appeal.flow.ts
[RIA-3682](https://tools.hmcts.net/jira/browse/RIA-3682)
```
[ ] Yes
[x] No
```
=> RIA-3682 fix e2e compilation error

e2e/features/record-application.feature
[RIA-3553](https://tools.hmcts.net/jira/browse/RIA-3553)
```
[ ] Yes
[x] No
```
=> RIA-3553 Allow appeal update details after appeal-submitted state

e2e/features/submit-appeal.feature
RIA-3628: HO Validation tab alignment in single table, Stateless
https://tools.hmcts.net/jira/browse/RIA-3628
```
[ ] Yes
[x ] No
```
=> RIA-3628: Remove Validation table headers fields for check

e2e/features/stepDefinitions/service/appeal.steps.ts, e2e/features/submit-appeal.feature, e2e/flows/start-appeal.flow.ts
[RIA-3486](https://tools.hmcts.net/jira/browse/RIA-3486)
Amended the start appeal checklist
```
[ ] Yes
[x] No
```
=> RIA-3486 e2e tests updated for start appeal checklist

e2e/features/add-addendum-evidence-admin-officer.feature, e2e/features/build-case.feature, e2e/features/customise-hearing-bundle.feature, e2e/features/decision-without-hearing.feature, e2e/features/ftpa-appellant-resident-judge-decision-and-reasons.feature, e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/ftpa-display-final-decision-scenario-10.feature, e2e/features/ftpa-display-final-decision-scenario-11.feature, e2e/features/ftpa-display-final-decision-scenario-12.feature, e2e/features/ftpa-display-final-decision-scenario-13.feature, e2e/features/ftpa-display-final-decision-scenario-14.feature, e2e/features/ftpa-display-final-decision-scenario-2.feature, e2e/features/ftpa-display-final-decision-scenario-3.feature, e2e/features/ftpa-display-final-decision-scenario-4.feature, e2e/features/ftpa-display-final-decision-scenario-5.feature, e2e/features/ftpa-display-final-decision-scenario-6.feature, e2e/features/ftpa-display-final-decision-scenario-7.feature, e2e/features/ftpa-display-final-decision-scenario-8.feature, e2e/features/ftpa-display-final-decision-scenario-9.feature, e2e/features/ftpa-respondent-leadership-judge-decision-and-reasons.feature, e2e/features/ftpa-respondent-resident-judge-decision-and-reasons.feature, e2e/features/mark-appeal-as-paid-after-listing.feature, e2e/flows/start-appeal.flow.ts, e2e/flows/start-decision-and-reasons.flow.ts
[RIA-3541](https://tools.hmcts.net/jira/browse/RIA-3541)
```
[ ] Yes
[x] No
```
=> RIA-3541 Ensure consistency for ia-ccd-e2e-tests

e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-appeal-home-office-validation.feature, e2e/features/submit-appeal.feature, e2e/flows/start-appeal.flow.ts
RIA-3390-3545: Handle different error scenario for Home Office validation flow
https://tools.hmcts.net/jira/browse/RIA-3390
https://tools.hmcts.net/jira/browse/RIA-3545
```
[ ] Yes
[ x] No
```
=> RIA-3390-3545: Handle different error scenario for Home Office validation flow

e2e/features/make-an-application.feature
[RIA-3457](https://tools.hmcts.net/jira/browse/RIA-3457)
LR and HO users make an application
```
[ ] Yes
[x] No
```
=> RIA-3457 Legal rep and Home office users make an application

e2e/features/reinstate-appeal.feature, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/stepDefinitions/service/reinstate-appeal.steps.ts, e2e/flows/reinstate-appeal.flow.ts, e2e/flows/start-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3039
RIA-3039 Reinstate after ended
```
[ ] Yes
[X] No
```
=> RIA-3039_Reinstate

e2e/features/ftpa-display-final-decision-scenario-1.feature
=> Fix for nightly build

e2e/features/decide-an-application.feature, e2e/features/stepDefinitions/service/make-an-application.steps.ts, e2e/flows/make-an-application.flow.ts
[RIA-3451](https://tools.hmcts.net/jira/browse/RIA-3451)
CaseOfficer and Judge decide an application
```
[ ] Yes
[x] No
```
=> RIA-3451 E2E for decide an application

e2e/features/ftpa-display-final-decision-scenario-1.feature
=> Removed nightly-tag from FTPA scenario.

e2e/features/flag-case-ftpa-admin-officer.feature, e2e/features/flag-case-ftpa-case-officer.feature, e2e/features/ftpa-decided-overview-tab-respondent-resident-judge.feature, e2e/features/ftpa-decided-remove-ftpa-flag-from-case.feature, e2e/features/ftpa-reheard-appellant-apply-for-respondent-ftpa-overview-tab.feature, e2e/features/ftpa-reheard-decision-appellant-overview-tab.feature, e2e/features/ftpa-reheard-respondent-apply-for-appellant-ftpa-overview-tab.feature, e2e/features/ftpa-two-reheard-decisions-overview-tab.feature
[RIA-3651](https://tools.hmcts.net/jira/browse/RIA-3651)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-3651 update ftpa tabs when decision set aside and reheard

e2e/features/ftpa-appeal-submitted-overview-tab-respondent-resident-judge.feature
[RIA-3652](https://tools.hmcts.net/jira/browse/RIA-3652)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3652 direction and state change ftpa decision reheard

e2e/features/case-list.feature, e2e/features/case-search.feature, e2e/features/edit-appeal.feature, e2e/features/start-appeal-address-validation.feature, e2e/features/start-appeal-alternate-paths.feature, e2e/features/start-appeal-basic-details.feature, e2e/features/start-appeal-confirmation.feature, e2e/features/start-appeal-grounds-of-appeal.feature, e2e/features/start-appeal-home-office-reference.feature, e2e/features/start-appeal-manual-address.feature, e2e/features/start-appeal-nationalities.feature, e2e/features/start-appeal-other-appeal-validation.feature, e2e/features/start-appeal.feature, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-appeal-home-office-validation.feature, e2e/flows/start-appeal.flow.ts
[RIA-3770](https://tools.hmcts.net/jira/browse/RIA-3770)
```
[ ] Yes
[x] No
```
=> RIA-3770 Update Home Office Reference Infographic

e2e/aip/ccd-service.ts, e2e/features/edit-appeal.feature, e2e/features/start-appeal-home-office-reference.feature, e2e/features/start-appeal.feature, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/flows/start-appeal.flow.ts
[RIA-3680](https://tools.hmcts.net/jira/browse/RIA-3680)
```
[ ] Yes
[x] No
```
=> RIA-3680 Add validation for Home Office References

e2e/features/case-progression-save-and-continue-false.feature, e2e/features/case-progression-save-and-continue-true.feature, e2e/features/ftpa-appeal-reheard-new-hearing-requirements.feature, e2e/features/record-agreed-hearing-requirements.feature, e2e/features/stepDefinitions/service/agreed-hearing-requirments.steps.ts, e2e/features/stepDefinitions/service/submit-hearing-requirments.steps.ts, e2e/features/submit-hearing-requirements.feature, e2e/features/update-hearing-adjustments.feature, e2e/features/update-hearing-requirements.feature, e2e/flows/submit-hearing-requirements.flow.ts
[RIA-3555](https://tools.hmcts.net/jira/browse/RIA-3555)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3555 new hearing requirements submitted

e2e/features/ftpa-appeal-reheard-new-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-tcw-review-requirements-no-path.feature, e2e/features/ftpa-appeal-reheard-tcw-review-requirements-yes-path.feature
[RIA-3582](https://tools.hmcts.net/jira/browse/RIA-3582)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3582 tcw review requirements

e2e/features/flag-case-ftpa-admin-officer.feature, e2e/features/flag-case-ftpa-case-officer.feature, e2e/features/ftpa-appeal-reheard-new-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-tcw-review-requirements-no-path.feature, e2e/features/ftpa-appeal-reheard-tcw-review-requirements-yes-path.feature, e2e/features/ftpa-appeal-submitted-overview-tab-respondent-resident-judge.feature, e2e/features/ftpa-decided-overview-tab-respondent-resident-judge.feature, e2e/features/ftpa-decided-remove-ftpa-flag-from-case.feature, e2e/features/ftpa-reheard-appeal-hearing-requirements-not-submitted.feature, e2e/features/ftpa-reheard-appellant-apply-for-respondent-ftpa-overview-tab.feature, e2e/features/ftpa-reheard-decision-appellant-overview-tab.feature, e2e/features/ftpa-reheard-respondent-apply-for-appellant-ftpa-overview-tab.feature, e2e/features/ftpa-two-reheard-decisions-overview-tab.feature, e2e/features/stepDefinitions/service/submit-hearing-requirments.steps.ts
[RIA-3386](https://tools.hmcts.net/jira/browse/RIA-3386)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3386 reheard hearing requirements not submitted

e2e/features/submit-appeal-home-office-reference-zero-padding-edit-appeal.feature, e2e/features/submit-appeal-home-office-reference-zero-padding-start-appeal.feature
https://tools.hmcts.net/jira/browse/RIA-3783
Home Office CID reference number zero padding changes
```
[ ] Yes
[X] No
```
=> RIA-3783: Home Office CID reference number zero padding

e2e/features/ftpa-appeal-reheard-ao-list-case-no-path-with-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-ao-list-case-no-path-without-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-ao-list-case-yes-path-with-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-edit-case-listing-with-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-edit-case-listing-without-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-edit-document.feature
[RIA-3683](https://tools.hmcts.net/jira/browse/RIA-3683)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3683 ao lists reheard case

e2e/features/ftpa-appeal-reheard-create-case-summary.feature
[RIA-3129](https://tools.hmcts.net/jira/browse/RIA-3129)
Create case summary as part of reheard
```
[ ] Yes
[x] No
```
=> Ria 3129 create case summary for reheard appeal

e2e/features/ftpa-appeal-reheard-finalbundling-add-document-to-bundle.feature, e2e/features/ftpa-appeal-reheard-finalbundling-list-case-no-path.feature, e2e/features/ftpa-appeal-reheard-finalbundling-list-case-yes-path.feature, e2e/features/ftpa-appeal-reheard-finalbundling-remove-document-to-bundle.feature
https://tools.hmcts.net/jira/browse/RIA-3130
```
[ ] Yes
[ X] No
```
=> Ria 3130 finalbundling to prehearing

e2e/features/ftpa-pre-hearing-to-decision.feature
[RIA-3131](https://tools.hmcts.net/jira/browse/RIA-3131)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3131 pre hearing to decision

e2e/features/ftpa-decision-to-decided.feature
[RIA-3132](https://tools.hmcts.net/jira/browse/RIA-3132)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3132 decision to decided

e2e/features/payment-validation-for-non-payment_appeal-type.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/start-appeal.flow.ts
[RIA-3516](https://tools.hmcts.net/jira/browse/RIA-3516)
RP and DC appeal type hearing options
```
[ ] Yes
[x] No
```
=> RIA-3516 e2e for RP and DC appeals hearing options

e2e/features/appeal-payment-failed.feature, e2e/features/duplicate-payment-error-handling.feature, e2e/features/mark-appeal-as-paid-after-listing.feature, e2e/features/mark-appeal-as-paid.feature, e2e/features/pa-appeal-pay-now.feature, e2e/features/pay-later-pa-submit-appeal-and-make-payment.feature, e2e/features/pay-now-submit.feature, e2e/features/pay-offline-by-card-pa.feature, e2e/features/payment-validation-for-non-payment_appeal-type.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-appeal-out-off-time-payment.feature, e2e/features/submit-appeal-with-offline-payment.feature, e2e/flows/start-appeal.flow.ts
[RIA-3014](https://tools.hmcts.net/jira/browse/RIA-3014)
Legal Rep submits an appeal with NO Fees remission
```
[ ] Yes
[x] No
```
=> RIA-3014 e2e Legal Rep submits an appeal with NO Fees remission

e2e/features/start-appeal-confirmation.feature, e2e/features/start-appeal.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-appeal-with-remission.feature, e2e/flows/start-appeal.flow.ts
[RIA-3088](https://tools.hmcts.net/jira/browse/RIA-3088)
Legal rep submits appeal with a remission
```
[ ] Yes
[x] No
```
=> RIA-3088 Legal rep submits appeal with a remission

e2e/features/submit-appeal-with-remission-types.feature
[RIA-3685](https://tools.hmcts.net/jira/browse/RIA-3685)
Legal rep submit appeal with asylum support remission
```
[ ] Yes
[x] No
```
=> RIA-3685 Legel rep submits appeal with asylum support remission

e2e/features/start-appeal.feature, e2e/features/submit-appeal-with-remission-types.feature
[RIA-2113](https://tools.hmcts.net/jira/browse/RIA-2113)
Legal rep submits appeal with Legal Aid remission
```
[ ] Yes
[x] No
```
=> RIA-2113 Legal rep submits appeal with Legal aid remission

e2e/features/allocate_a_case.feature
Test for allocating a case to me
https://tools.hmcts.net/jira/browse/RWA-137
```
[ ] Yes
[X] No
```
=> RWA-137 Allocate a case to me

e2e/flows/start-appeal.flow.ts
Remission check is removed if the fee and payments feature is not enabled.
```
[ ] Yes
[ ] No
```
=> Remissions check removed on isfeePaymentEnabled is false

e2e/features/adjourn-without-a-date.feature, e2e/features/stepDefinitions/service/overview.steps.ts
[RIA-3738](https://tools.hmcts.net/jira/browse/RIA-3738)
```
[ ] Yes
[x] No
```
=> RIA-3738 Link for adjournment takes user to a blank page

e2e/features/submit-appeal-with-remission-types.feature, e2e/flows/start-appeal.flow.ts
[RIA-3686](https://tools.hmcts.net/jira/browse/RIA-3686)
Legal rep submits appeal using one of the below remission types
• Section 17
• Section 20
• Home Office waiver
```
[ ] Yes
[x] No
```
=> RIA-3686 Legal rep submits appeal with other remission types

e2e/features/submit-appeal-with-remission-types.feature
[RIA-3084](https://tools.hmcts.net/jira/browse/RIA-3084)
Legal rep submits appeal with help with fees
```
[ ] Yes
[x] No
```
=> RIA-3084 Legal rep submits appeal with help with fees

e2e/features/submit-appeal-with-remission-types.feature
RIA-3085 Legal rep submit appeal with exceptional circumstances remission for fees
https://tools.hmcts.net/jira/browse/RIA-3085
```
[ ] Yes
[ x] No
```
=> RIA-3085 Legal rep submit appeal with exceptional circumstances remission for fees

e2e/features/record-remission-decision.feature, e2e/flows/start-appeal.flow.ts
[RIA-3517](https://tools.hmcts.net/jira/browse/RIA-3517)
Admin officer record remission decision
```
[ ] Yes
[x] No
```
=> RIA-3517 Admin officer record remission decision

e2e/features/record-remission-decision.feature
[RIA-3829](https://tools.hmcts.net/jira/browse/RIA-3829)
Overview tabs for Record remission decision updated
```
[ ] Yes
[x] No
```
=> RIA-3829 Record remission decision overview tabs

e2e/features/flag-case.feature, e2e/features/stepDefinitions/ccd-page.steps.ts
=> Fix for flag-a-case nightly regression tests.

e2e/pages/any.page.ts
=> Fix tab selection to handle ExUI mat tabs.

e2e/pages/idam-sign-in.page.ts
N/A
new selector to log in click
```
[ ] Yes
[x] No
```
=> Idam simulator selector

Jenkinsfile_nightly
=> Increase nightly build time

e2e/features/case-progression-save-and-continue-false.feature, e2e/features/case-progression-save-and-continue-true.feature, e2e/features/request-respondent-evidence.feature
https://tools.hmcts.net/jira/browse/RIA-3821
RIA-3821 ooc bundle_direction
```
[ ] Yes
[X] No
```
=> RIA-3821_ooc_bundle_direction

e2e/features/home-office-users-view-all-tabs.feature, e2e/features/upload-respondent-evidence.feature
https://tools.hmcts.net/jira/browse/RIA-3837
RIA-3837 ooc legal rep
```
[ ] Yes
[X] No
```
=> Ria 3837 ooc legal rep

e2e/features/case-progression-save-and-continue-false.feature, e2e/features/case-progression-save-and-continue-true.feature, e2e/features/home-office-users-view-all-tabs.feature, e2e/features/request-respondent-review.feature
https://tools.hmcts.net/jira/browse/RIA-3836
RIA-3836 ooc content
```
[ ] Yes
[X] No
```
=> RIA-3836_ooc_content

e2e/features/add-appeal-response.feature, e2e/features/case-progression-save-and-continue-false.feature, e2e/features/case-progression-save-and-continue-true.feature
https://tools.hmcts.net/jira/browse/RIA-3838
RIA-3838 ooc_content
```
[ ] Yes
[X] No
```
=> RIA-3838_ooc_content

e2e/features/list-case-without-hearing-requirements.feature
https://tools.hmcts.net/jira/browse/RIA-3839
RIA-3839 ooc content for Submit Hearing Requirements direction
```
[ ] Yes
[X] No
```
=> Ria 3839 ooc content

e2e/features/ftpa-appeal-submitted-overview-tab-respondent-resident-judge.feature
https://tools.hmcts.net/jira/browse/RIA-3840
RIA-3840 ooc content Reheard Submit Hearing Requirements
```
[ ] Yes
[X] No
```
=> RIA-3840_ooc_content

e2e/features/build-case.feature, e2e/features/submit-case.feature
https://tools.hmcts.net/jira/browse/RIA-3841
RIA-3841 ooc content build case
```
[ ] Yes
[X] No
```
=> RIA-3841_ooc_content

e2e/features/new-share-a-case.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/features/stepDefinitions/service/new-share-a-case.steps.ts, e2e/features/stepDefinitions/share-case.steps.ts, e2e/flows/authentication.flow.ts, e2e/flows/new-share-a-case.flow.ts, e2e/ia.conf.js, e2e/pages/share-case.page.ts, e2e/support/customWaits.js
[RIA-3485](https://tools.hmcts.net/jira/browse/RIA-3845)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-3845 new share case

Jenkinsfile_nightly, e2e/browser.platform.matrix.js, e2e/enums/wait.ts, e2e/features.crossbrowser.conf.js, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/stepDefinitions/service/appellant.steps.ts, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/submit-appeal.feature, e2e/flows/start-appeal.flow.ts, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/RIA-3991
```
[ ] Yes
[x] No
```
Jenkins Run result : https://build.platform.hmcts.net/view/IA/job/HMCTS_Nightly_IAC/job/ia-ccd-e2e-tests/view/change-requests/job/PR-408/10/
Run Report : https://build.platform.hmcts.net/view/IA/job/HMCTS_Nightly_IAC/job/ia-ccd-e2e-tests/view/change-requests/job/PR-408/10/IA_20Service_20Cross_20Browser_20Tests/
=> Support for crossbrowser testing.

Jenkinsfile_nightly
=> fix jenkins nightly for xbrowser.

e2e/features.crossbrowser.conf.js, yarn.lock
=> changes to versions.

e2e/features/manage-fee-update.feature, e2e/features/stepDefinitions/service/mark-appeal-as-paid.steps.ts, e2e/features/stepDefinitions/service/submit-appeal.steps.ts, e2e/flows/mark-appeal-as-paid.flow.ts
[RIA-3792](https://tools.hmcts.net/jira/browse/RIA-3792)
Case-officer and Admin-officer manage fee update
```
[ ] Yes
[x] No
```
=> RIA-3792 Case officer and Admin officer manage a fee update

e2e/features/manage-fee-update.feature
[RIA-3790](https://tools.hmcts.net/jira/browse/RIA-3790)
Manage fee update with option feeUpdateRecorded for Case-officer and Admin-officer
```
[ ] Yes
[x] No
```
=> RIA-3790 Manage fee update with option feeUpdateRecorded

e2e/features/manage-fee-update.feature, e2e/features/mark-appeal-as-paid-after-listing.feature, e2e/features/mark-appeal-as-paid.feature, e2e/features/record-remission-decision.feature, e2e/flows/mark-appeal-as-paid.flow.ts
[RIA-3793](https://tools.hmcts.net/jira/browse/RIA-3793)
Case-officer and Admin-officer manageFeeUpdate for the type Appeal not valid
```
[ ] Yes
[x] No
```
=> RIA-3793 Manage fee update for the type appeal not valid

e2e/features/belfast-hearing-centre.feature, e2e/features/stepDefinitions/service/request-case-building.steps.ts, e2e/flows/request-case-building.flow.ts, e2e/flows/upload-respondent-evidence.flow.ts
[RIA-3810](https://tools.hmcts.net/jira/browse/RIA-3810)
Belfast hearing centre added
```
[ ] Yes
[x] No
```
=> RIA-3810 new hearing centre Belfast

e2e/features/request-case-building.feature
[RIA-3907](https://tools.hmcts.net/jira/browse/RIA-3907)
HomeOffice progress svg images
```
[ ] Yes
[x] No
```
=> RIA-3907 HomeOffice svg image updated

e2e/features/email-address-validation.feature, e2e/features/stepDefinitions/ccd-form-page.steps.ts, e2e/fields/ccd-write-email-field-finder.ts, e2e/fields/ccd-write-email-field.ts, e2e/fields/fields.ts
[RIA-3948](https://tools.hmcts.net/jira/browse/RIA-3948)
Email address regex validation
```
[ ] Yes
[x] No
```
=> RIA-3948 Contact preference email address validation test

e2e/features/appeal-payment-failed.feature, e2e/features/case-progression-save-and-continue-false.feature, e2e/features/case-progression-save-and-continue-true.feature, e2e/features/edit-appeal.feature, e2e/features/ftpa-appeal-reheard-new-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-no-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-update-hearing-requirements.feature, e2e/features/ftpa-appeal-reheard-without-hearing-requirements-no-recordings.feature, e2e/features/ftpa-appeal-reheard-without-hearing-requirements.feature, e2e/features/ftpa-appeal-submitted-overview-tab-respondent-resident-judge.feature, e2e/features/ftpa-pre-hearing-to-decision.feature, e2e/features/ftpa-reheard-appeal-hearing-requirements-not-submitted.feature, e2e/features/list-case-without-hearing-requirements.feature, e2e/features/mark-appeal-as-paid.feature, e2e/features/pay-later-pa-submit-appeal-and-make-payment.feature, e2e/features/pay-now-submit.feature, e2e/features/pay-offline-by-card-pa.feature, e2e/features/request-case-building.feature, e2e/features/send-case-preHearing-bundle-failed.feature, e2e/features/start-appeal.feature, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/features/submit-appeal-new-appellant-tab.feature, e2e/features/submit-appeal-with-offline-payment.feature, e2e/features/submit-hearing-requirements.feature
[RIA-3910](https://tools.hmcts.net/jira/browse/RIA-3910)
```
[ ] Yes
[x] No
```
=> RIA-3910 Upload LR progress bar SVG images to Github

e2e/features/case-history-tab.feature
[RIA-1427](https://tools.hmcts.net/jira/browse/RIA-1427)
Case history tab
```
[ ] Yes
[x] No
```
=> RIA-1427 case history tab viewer test

e2e/features/start-appeal-out-of-country-selection.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/start-appeal.flow.ts, e2e/ia.conf.js
RIA-3876:Out of country screening questions
https://tools.hmcts.net/jira/browse/RIA-3876
```
[ ] Yes
[ x] No
```
=> RIA-3876:Out of country screening questions

e2e/features/case-progression-save-and-continue-false.feature, e2e/features/case-progression-save-and-continue-true.feature, e2e/features/upload-home-office-appeal-response.feature
[RIA-3729](https://tools.hmcts.net/jira/browse/RIA-3729)
```
[ ] Yes
[x] No
```
=> RIA-3729 Modify overview tab for HO in respondent review

e2e/features/start-appeal-out-of-country-removal-of-client.feature, e2e/flows/start-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3877
See ticket
```
[ ] Yes
[X ] No
```
=> Ria 3877 ooc

e2e/features/start-appeal-out-of-country-protection-claim.feature, e2e/features/start-appeal-out-of-country-removal-of-client.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/start-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3861
RIA-3861 - LR submits a OOC appeal - Protection claim
```
[ ] Yes
[X] No
```
=> Ria 3861 ooc refuse

e2e/features/start-appeal-out-of-country-late-submission.feature, e2e/features/start-appeal-out-of-country-no-sponsor.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/stepDefinitions/service/submit-appeal.steps.ts, e2e/flows/start-appeal.flow.ts, e2e/flows/submit-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3954
see ticket
```
[ ] Yes
[ X] No
```
=> Ria 3954 ooc

e2e/features/edit-appeal-out-of-country.feature, e2e/features/stepDefinitions/service/edit-appeal.steps.ts, e2e/flows/start-appeal.flow.ts
RIA-3878: Edit appeal for out of country
https://tools.hmcts.net/jira/browse/RIA-3878
```
[ ] Yes
[ x] No
```
=> RIA-3878: Edit appeal for out of country

e2e/flows/start-appeal.flow.ts
Removed duplicate function
```
[ ] Yes
[X] No
```
=> Removed duplicate function

e2e/features/extend-wiremock.feature, e2e/features/new-share-a-case.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/flows/authentication.flow.ts, e2e/ia.conf.js
[RIA-3959](https://tools.hmcts.net/jira/browse/RIA-3959)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3959 extend wiremock

e2e/features/remote-hearing.feature, e2e/features/stepDefinitions/service/submit-hearing-requirments.steps.ts, e2e/features/submit-hearing-requirements.feature, e2e/flows/submit-hearing-requirements.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3718
LR adds remote hearing option to Submit hearing requirement
```
[ ] Yes
[x ] No
```
=> RIA-3718: Add remote hearing option to Submit hearing requirement

e2e/features/flag-case.feature
=> added waits

e2e/features/record-agreed-hearing-requirements.feature, e2e/features/remote-hearing.feature, e2e/features/stepDefinitions/service/agreed-hearing-requirments.steps.ts, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-hearing-requirements.feature, e2e/flows/record-agreed-requirements.flow.ts, e2e/flows/start-appeal.flow.ts
https://tools.hmcts.net/jira/browse/RIA-3719
TCW Review remote hearing in record hearing adjustment
```
[ ] Yes
[ x] No
```
=> RIA-3719:Review remote hearing in record hearing adjustment

e2e/features/flag-case.feature
=> Added s94b flag scenario

e2e/features/remote-hearing-edit-listing.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/features/stepDefinitions/service/list-case.steps.ts, e2e/flows/list-case.flow.ts
[RIA-3722](https://tools.hmcts.net/jira/browse/RIA-3722)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3722 edit listing

e2e/features/notice-of-change.feature, e2e/features/stepDefinitions/authentication.steps.ts, e2e/features/stepDefinitions/service/notice-of-change.steps.ts, e2e/pages/notice-of-change.page.ts
[RIA-3745](https://tools.hmcts.net/jira/browse/RIA-3745)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3745 notice of change

e2e/features/noc-remove-representation-after-listing.feature, e2e/features/noc-remove-representation-non-org-legal-rep.feature, e2e/features/noc-remove-representation.feature, e2e/features/stepDefinitions/service/notice-of-change.steps.ts, e2e/pages/notice-of-change.page.ts
[RIA-3731](https://tools.hmcts.net/jira/browse/RIA-3731)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3731 remove representation

e2e/features/noc-remove-representation-after-listing-tcw.feature, e2e/features/noc-remove-representation-tcw.feature
[RIA-3951](https://tools.hmcts.net/jira/browse/RIA-3951)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3951 remove legal rep

e2e/features/request-fee-remission.feature, e2e/features/stepDefinitions/service/record-remission-decision.steps.ts, e2e/flows/mark-appeal-as-paid.flow.ts, e2e/flows/record-remission-decision.flow.ts
[RIA-3218](https://tools.hmcts.net/jira/browse/RIA-3218)
Legal rep apply for a late remission
```
[ ] Yes
[x] No
```
=> RIA-3218 Legal rep apply for a late remission

yarn.lock
=> fix for security vulnerabilities

e2e/features/record-remission-decision.feature, e2e/features/stepDefinitions/service/record-remission-decision.steps.ts, e2e/features/stepDefinitions/service/request-fee-remission.steps.ts, e2e/flows/record-remission-decision.flow.ts, e2e/flows/request-fee-remission.flow.ts
[RIA-3830](https://tools.hmcts.net/jira/browse/RIA-3830)
Admin officer records remission decision for a late remission
```
[ ] Yes
[x] No
```
=> RIA-3830 Admin officer records remission decision for a late remission

e2e/features/manage-fee-update.feature
[RIA-3794](https://tools.hmcts.net/jira/browse/RIA-3794)
As a case-officer manage fee update for fee remission changed.
```
[ ] Yes
[x] No
```
=> RIA-3794 Manage fee update for fee remission changed

e2e/features/manage-fee-update.feature
RIA-3795:Manage fee update, fee update status options flow
https://tools.hmcts.net/jira/browse/RIA-3795
```
[ ] Yes
[x ] No
```
=> RIA-3795:Manage fee update, fee update status options flow

e2e/features/manage-fee-update.feature
RIA-3813 manage fee update refund instructed
https://tools.hmcts.net/jira/browse/RIA-3813
```
[ ] Yes
[ x] No
```
=> RIA-3813 manage fee update refund instructed

e2e/features/manage-fee-update.feature
RIA-3814: Manage fee update post refund instructed
https://tools.hmcts.net/jira/browse/RIA-3814
```
[ ] Yes
[ x] No
```
=> RIA-3814: Manage fee update post refund instructed flow

e2e/features/remote-hearing-update-hearing-requirements.feature, e2e/flows/submit-hearing-requirements.flow.ts
[RIA-3721](https://tools.hmcts.net/jira/browse/RIA-3721)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3721 update hearing requirements

e2e/features/manage-fee-update.feature
[RIA-3882](https://tools.hmcts.net/jira/browse/RIA-3882)
Admin officer journey chooses fee update not required after additional fee required
```
[ ] Yes
[x] No
```
=> RIA-3882 Admin officer journey chooses fee update not required after additional fee required

e2e/features/manage-fee-update.feature
RIA-3880:Manage fee update not allowed post fee update not required
https://tools.hmcts.net/jira/browse/RIA-3880
```
[ ] Yes
[x ] No
```
=> RIA-3880:Manage fee update not allowed post fee update not required

e2e/features/stepDefinitions/service/submit-hearing-requirments.steps.ts, e2e/features/submit-hearing-requirements-giving-evidence-in-county-flow-extraction.feature, e2e/features/submit-hearing-requirements-giving-evidence-in-county.feature, e2e/features/submit-hearing-requirements-giving-evidence-ooc.feature, e2e/features/submit-hearing-requirements-giving-evidence-out-of-county-flow-extraction.feature, e2e/flows/submit-hearing-requirements.flow.ts
[RIA-3825](https://tools.hmcts.net/jira/browse/RIA-3825)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3825 ooc hearing requirements

e2e/flows/start-appeal.flow.ts
[RIA-3854](https://tools.hmcts.net/jira/browse/RIA-3854)
Home office decision document made mandatory
```
[ ] Yes
[x] No
```
=> RIA-3854 Notice of decision document is made mandatory

e2e/features/record-out-of-time-decision.feature, e2e/flows/start-appeal.flow.ts
[RIA-4042](https://tools.hmcts.net/jira/browse/RIA-4042)
Case-officer records appeal out of time decision
```
[ ] Yes
[x] No
```
=> RIA-4042 Case officer record out of time decision

e2e/features/generate-hearing-bundle.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/stepDefinitions/service/edit-appeal.steps.ts, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/request-hearing-requirements.flow.ts, e2e/flows/start-appeal.flow.ts, e2e/flows/submit-hearing-requirements.flow.ts
N/A
Refactoring e2e for new features released recently
```
[ ] Yes
[x] No
```
=> Refactoring e2e for new features released recently

e2e/features/stepDefinitions/service/appeal.steps.ts, e2e/features/stepDefinitions/service/appellant.steps.ts, e2e/features/stepDefinitions/service/overview.steps.ts, e2e/fields/ccd-write-date-field.ts, e2e/fields/ccd-write-dynamic-list-field-finder.ts, e2e/fields/ccd-write-dynamic-list-field.ts, e2e/fields/fields.ts, e2e/flows/start-appeal.flow.ts, e2e/flows/submit-hearing-requirements.flow.ts, e2e/flows/upload-respondent-evidence.flow.ts, e2e/pages/any.page.ts, e2e/support/customWaits.js
=> Flaky tests fix

e2e/features/generate-hearing-bundle.feature, e2e/features/stepDefinitions/service/edit-appeal.steps.ts, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/fields/ccd-write-date-field.ts, e2e/flows/start-appeal.flow.ts, e2e/flows/submit-hearing-requirements.flow.ts, e2e/ia.conf.js
N/A
e2e refactoring
```
[ ] Yes
[x] No
```
=> e2e refactoring

yarn.lock
=> fix for Dependency check failures

e2e/browser.platform.matrix.js, e2e/features.crossbrowser.conf.js, e2e/flows/start-appeal.flow.ts, e2e/ia.conf.js
1. Support for file upload through saucelabs.
2. Remove SauceProxy since Jenkins proxy is not enabled now.
3. Enabled Capture Performance when run through Saucelabs.
```
[ ] Yes
[x] No
```
=> Changes to get tests passing through Saucelabs.

e2e/browser.platform.matrix.js
Remove IE11 from Cross Browser Tests
```
[ ] Yes
[x] No
```
=> Remove IE11 from saucelabs test.

yarn.lock
=> fix for Dependency check failure

e2e/features/pba-refactor-edit-payment-method-ea-appeal.feature, e2e/features/pba-refactor-edit-payment-method-hu-appeal.feature, e2e/features/pba-refactor-edit-payment-method-pa-appeal.feature, e2e/features/pba-refactor-pay-and-submit-ea-appeal.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature, e2e/features/pba-refactor-pay-for-appeal-ea-appeal.feature, e2e/features/pba-refactor-pay-for-appeal-hu-appeal.feature, e2e/features/pba-refactor-pay-later-pa-appeal.feature, e2e/features/pba-refactor-pay-offline-ea-appeal.feature, e2e/features/pba-refactor-pay-offline-hu-appeal.feature, e2e/features/pba-refactor-pay-offline-pa-appeal.feature, e2e/features/pba-refactor-payment-appeal-pa-appeal.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/flows/start-appeal.flow.ts
[RIA-4468](https://tools.hmcts.net/jira/browse/RIA-4468)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-4468 duplicate pba payments

e2e/features/decision-without-hearing.feature
[RIA-4473](https://tools.hmcts.net/jira/browse/RIA-4473)
```
[ ] Yes
[x] No
```
=> RIA-4473 Decision without hearing route

e2e/features/noc-previous-representation.feature, e2e/features/noc-update-representative-details.feature, e2e/pages/any.page.ts
[RIA-4293](https://tools.hmcts.net/jira/browse/RIA-4293)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 4293 noc prompt to update details

e2e/features/ftpa-decision-refused-and-not-admitted.feature
[RIA-4404](https://tools.hmcts.net/jira/browse/RIA-4404)
FTPA tab fields for refused and not-admitted outcomes
```
[ ] Yes
[x] No
```
=> RIA-4404 FTPA tab fields for refused and not-admitted outcomes

e2e/features/edit-appeal-out-of-country.feature, e2e/features/start-appeal-out-of-country-late-submission.feature, e2e/features/start-appeal-out-of-country-no-address-no-sponsor.feature, e2e/features/start-appeal-out-of-country-no-sponsor.feature, e2e/features/start-appeal-out-of-country-protection-claim.feature, e2e/features/start-appeal-out-of-country-removal-of-client.feature, e2e/flows/start-appeal.flow.ts, tslint.json
[RIA-4372](https://tools.hmcts.net/jira/browse/RIA-4372)
```
[ ] Yes
[x] No
```
=> RIA-4372 Add Home Office decision type into OOC flow

e2e/features/pba-refactor-edit-payment-method-ea-appeal.feature, e2e/features/pba-refactor-edit-payment-method-hu-appeal.feature, e2e/features/pba-refactor-edit-payment-method-pa-appeal.feature, e2e/features/pba-refactor-pay-and-submit-ea-appeal.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature, e2e/features/pba-refactor-pay-for-appeal-ea-appeal.feature, e2e/features/pba-refactor-pay-for-appeal-hu-appeal.feature, e2e/features/pba-refactor-payment-appeal-pa-appeal.feature, e2e/flows/authentication.flow.ts, e2e/flows/start-appeal.flow.ts
[RIA-4679](https://tools.hmcts.net/jira/browse/RIA-4679)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-4679 update 'How to pay' wording

e2e/features/case-progression-save-and-continue-false.feature, e2e/features/case-progression-save-and-continue-true.feature, e2e/features/upload-home-office-appeal-response.feature
[RIA-4642](https://tools.hmcts.net/jira/browse/RIA-4642)
```
[ ] Yes
[x] No
```
=> RIA-4642 HO Review Request: Home Office Overview page changes (LR and AiP flows)

yarn.lock
=> fix for Dependency check

e2e/features/generate-upper-tribunal-bundle-granted.feature, e2e/features/generate-upper-tribunal-bundle-not-admitted.feature, e2e/features/generate-upper-tribunal-bundle-partially-granted.feature, e2e/features/generate-upper-tribunal-bundle-refused.feature, e2e/flows/pay-and-submit-appeal.flow.ts, e2e/flows/send-decision-and-reasons.flow.ts
[RIA-4351](https://tools.hmcts.net/jira/browse/RIA-4351)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-4351 generate upper tribunal bundle

yarn.lock
=> BAU fix yarn lock

package.json, yarn.lock
=> Fix nightly dependency checks

Jenkinsfile_nightly, e2e/features/add-case-note.feature, e2e/features/decide-an-application.feature, e2e/features/end-appeal.feature, e2e/features/link-appeal.feature, e2e/features/make-an-application.feature, e2e/features/new-share-a-case.feature, e2e/features/notice-of-change.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/request-respondent-evidence.feature, e2e/features/request-respondent-review.feature, e2e/features/update-legal-representatives-details.feature, e2e/features/upload-additional-evidence-home-office.feature, yarn.lock
=> Ria 3758 2

Jenkinsfile_nightly, e2e/features/stepDefinitions/authentication.steps.ts, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/upload-additional-evidence-home-office.feature, e2e/pages/any.page.ts, e2e/pages/ccd.page.ts
=> wait for the spinner element to hide

e2e/features/payment-validation-for-non-payment_appeal-type.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature, e2e/features/pba-refactor-pay-later-pa-appeal.feature, e2e/features/pba-refactor-pay-offline-ea-appeal.feature, e2e/features/pba-refactor-pay-offline-hu-appeal.feature, e2e/features/pba-refactor-pay-offline-pa-appeal.feature, e2e/features/record-remission-decision.feature, e2e/features/stepDefinitions/service/start-appeal.steps.ts, e2e/features/submit-appeal-with-remission-types.feature, e2e/features/submit-appeal-with-remission.feature, e2e/flows/start-appeal.flow.ts
=> Regression fixes

e2e/flows/start-appeal.flow.ts
=> got rid of close and return to case details as necessary

e2e/features/decide-an-application.feature, e2e/features/ftpa-decision-refused-and-not-admitted.feature, e2e/features/link-appeal.feature, e2e/features/make-an-application.feature, e2e/features/notice-of-change.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/request-respondent-evidence.feature, e2e/features/request-respondent-review.feature, e2e/features/update-legal-representatives-details.feature, e2e/features/upload-additional-evidence-home-office.feature
=> changed 5s wait to 8s

e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/make-an-application.feature, e2e/features/new-share-a-case.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature, e2e/features/stepDefinitions/ccd-page.steps.ts
Reverts hmcts/ia-ccd-e2e-tests#496
=> Revert "Nightly dev functional fixes 19/01/22"

e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/make-an-application.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature
=> to get functionals working

e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/make-an-application.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/upload-additional-evidence-home-office.feature
Various tweaks for nightly functional tests to pass more often
```
[ ] Yes
[x] No
```
=> Nighly dev fix190122

e2e/features/new-share-a-case.feature, e2e/features/notice-of-change.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/flows/prepare-decision-and-reasons.flow.ts
Few fixes to reduce build failures for demo regression and AAT nightly
```
[ ] Yes
[x] No
```
=> Nightly demo fix2102

e2e/features/new-share-a-case.feature, e2e/features/notice-of-change.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/flows/prepare-decision-and-reasons.flow.ts
minor tweaks for demo regression stability
```
[ ] Yes
[x] No
```
=> tweaks for regression on demo stability

e2e/features/add-case-note.feature, e2e/features/decide-an-application.feature, e2e/features/end-appeal.feature, e2e/features/flag-case.feature, e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/link-appeal.feature, e2e/features/make-an-application.feature, e2e/features/new-share-a-case.feature, e2e/features/notice-of-change.feature, e2e/features/start-decisions-and-reasons.feature
Changed/added wait before create a case to bypass spinner issue
```
[ ] Yes
[x] No
```
=> wait 10s before create new case on nightly

e2e/features/add-case-note.feature, e2e/features/decide-an-application.feature, e2e/features/end-appeal.feature, e2e/features/flag-case.feature, e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/link-appeal.feature, e2e/features/new-share-a-case.feature, e2e/features/notice-of-change.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/upload-additional-evidence-home-office.feature
tweaks to try and resolve timeouts etc and achieve green nightly builds
```
[ ] Yes
[x] No
```
=> Nightly aat220222

e2e/features/add-case-note.feature, e2e/features/decide-an-application.feature, e2e/features/end-appeal.feature, e2e/features/flag-case.feature, e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/link-appeal.feature, e2e/features/list-case.feature, e2e/features/make-an-application.feature, e2e/features/new-share-a-case.feature, e2e/features/notice-of-change.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature, e2e/features/request-respondent-evidence.feature, e2e/features/request-respondent-review.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/submit-appeal.feature, e2e/features/submit-change-hearing-centre.feature, e2e/features/submit-hearing-requirements.feature, e2e/features/update-legal-representatives-details.feature, e2e/features/upload-additional-evidence-home-office.feature, e2e/features/wa-iac-workflow-review-appeal.feature
few waits and split up start decision and reasons for stability in nightly builds
```
[ ] Yes
[x] No
```
=> tweaks for nightly consistency

e2e/features/add-case-note.feature, e2e/features/decide-an-application.feature, e2e/features/end-appeal.feature, e2e/features/flag-case.feature, e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/link-appeal.feature, e2e/features/list-case.feature, e2e/features/make-an-application.feature, e2e/features/new-share-a-case.feature, e2e/features/notice-of-change.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature, e2e/features/request-respondent-evidence.feature, e2e/features/request-respondent-review.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/submit-appeal.feature, e2e/features/submit-hearing-requirements.feature, e2e/features/update-legal-representatives-details.feature, e2e/features/upload-additional-evidence-home-office.feature
tweaking pay and submit flows to avoid timeout
```
[ ] Yes
[x] No
```
=> Nightly240222

e2e/features/add-case-note.feature, e2e/features/decide-an-application.feature, e2e/features/end-appeal.feature, e2e/features/flag-case.feature, e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/link-appeal.feature, e2e/features/make-an-application.feature, e2e/features/new-share-a-case.feature, e2e/features/notice-of-change.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature, e2e/features/request-respondent-evidence.feature, e2e/features/request-respondent-review.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/submit-appeal.feature, e2e/features/update-legal-representatives-details.feature, e2e/features/upload-additional-evidence-home-office.feature
=> close and return to case details before pay and submit

e2e/features/add-case-note.feature, e2e/features/decide-an-application.feature, e2e/features/end-appeal.feature, e2e/features/flag-case.feature, e2e/features/ftpa-display-final-decision-scenario-1.feature, e2e/features/link-appeal.feature, e2e/features/make-an-application.feature, e2e/features/new-share-a-case.feature, e2e/features/notice-of-change.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature, e2e/features/request-respondent-evidence.feature, e2e/features/request-respondent-review.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/submit-appeal.feature, e2e/features/update-legal-representatives-details.feature, e2e/features/upload-additional-evidence-home-office.feature
tweaks to get green nightly build
```
[ ] Yes
[x] No
```
=> Nightly fix0103

e2e/features/new-share-a-case.feature, e2e/features/stepDefinitions/share-case.steps.ts, e2e/pages/share-case.page.ts
=> Nightly fix0403

yarn.lock
=> fix for dependency failure

e2e/features/new-share-a-case.feature, e2e/features/stepDefinitions/service/new-share-a-case.steps.ts, e2e/flows/new-share-a-case.flow.ts, e2e/pages/share-case.page.ts
share case fix
```
[ ] Yes
[x] No
```
=> share a case feature test fix

e2e/features/submit-bail-application-legal-rep.feature
https://tools.hmcts.net/jira/browse/RIA-5661
added LR submission
```
[ ] Yes
[x] No
```
=> submit application as LR

e2e/features/case-progression-admin.feature, e2e/features/case-progression-judge.feature, e2e/features/case-progression-save-and-continue-false.feature, e2e/features/case-progression-save-and-continue-true.feature, e2e/features/reinstate-appeal.feature, e2e/features/upload-home-office-appeal-response.feature
=> appeal outcome page addition

e2e/features/new-share-a-case.feature, e2e/features/stepDefinitions/service/new-share-a-case.steps.ts, e2e/flows/new-share-a-case.flow.ts, e2e/pages/share-case.page.ts
=> Share case master fix

e2e/features.parallel.conf.js, reporter/customReporter.js
=> adding protractor retry

e2e/features.parallel.conf.js, e2e/support/hooks.js, reporter/customReporter.js
=> Protractor retry

e2e/features/bails-add-a-case-note.feature, e2e/features/bails-record-the-decision.feature, e2e/features/bails-submit-bail-application-admin-officer.feature, e2e/features/bails-submit-bail-application-home-office.feature, e2e/features/bails-submit-bail-application-legal-rep.feature, e2e/features/bails-upload-bail-summary.feature
=> record decision 7 scenarios complete

e2e/features/flag-case.feature, e2e/pages/share-case.page.ts
=> NIghtly test fix from flag a case and share a case

Jenkinsfile_nightly
=> changing nightly timing

e2e/features/bails-change-direction-due-date.feature, e2e/features/bails-move-application-to-decided.feature, e2e/features/bails-record-the-decision.feature, e2e/features/bails-upload-documents.feature
=> few bails test fixes/updates

Jenkinsfile_nightly, e2e/features.conf.js, e2e/features.crossbrowser.conf.js, e2e/features.parallel.conf.js, e2e/pages/any.page.ts, e2e/support/hooks.js, package.json, reporter/customReporter.js, yarn.lock
=> retry failed functional scenarios fix for master

e2e/features/edit-appeal-out-of-country.feature, e2e/flows/start-appeal.flow.ts, package.json
=> edit appeal fix

e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/flows/start-appeal.flow.ts
=> nightly fixes

e2e/features/edit-appeal-out-of-country.feature, e2e/features/pba-refactor-pay-and-submit-hu-appeal.feature, e2e/features/pba-refactor-pay-and-submit-pa-appeal.feature, package.json, yarn.lock
=> Master nightly fix

e2e/features.crossbrowser.conf.js, e2e/features.parallel.conf.js, package.json, yarn.lock
=> change test report format

e2e/features/add-case-note.feature, e2e/features/decide-an-application.feature, e2e/features/flag-case.feature, e2e/features/link-appeal.feature, e2e/features/make-an-application.feature, e2e/features/update-legal-representatives-details.feature
Removed alert checks due to inconsistency
```
[ ] Yes
[x] No
```
=> nightly fix

yarn.lock
=> fix for dependency checks failure

yarn.lock
=> fix for build failure

Jenkinsfile_nightly, e2e/features/generate-upper-tribunal-bundle-granted.feature, e2e/features/generate-upper-tribunal-bundle-not-admitted.feature, e2e/features/generate-upper-tribunal-bundle-partially-granted.feature, e2e/features/generate-upper-tribunal-bundle-refused.feature, e2e/features/legal-rep-online-payments-pay-by-card-ea-appeal.feature, e2e/features/legal-rep-online-payments-pay-by-card-hu-appeal.feature, e2e/features/legal-rep-online-payments-pay-by-card-pa-appeal.feature, e2e/features/legal-rep-online-payments-pay-by-pba-ea-appeal.feature, e2e/features/legal-rep-online-payments-pay-by-pba-hu-appeal.feature, e2e/features/legal-rep-online-payments-pay-by-pba-pa-appeal.feature, e2e/features/manage-fee-update.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/stepDefinitions/service/submit-appeal.steps.ts, e2e/features/submit-appeal.feature, e2e/flows/pay-and-submit-appeal.flow.ts, e2e/flows/start-appeal.flow.ts, package.json
https://tools.hmcts.net/jira/browse/RIA-6104
```
[ ] Yes
[x] No
```
=> testing the newly added and changed files

e2e/features/bails-add-a-case-note.feature, e2e/features/bails-change-direction-due-date.feature, e2e/features/bails-edit-application-post-submit.feature, e2e/features/bails-edit-application-pre-submit.feature, e2e/features/bails-edit-documents.feature, e2e/features/bails-end-application.feature, e2e/features/bails-make-new-application.feature, e2e/features/bails-move-application-to-decided.feature, e2e/features/bails-notice-of-change.feature, e2e/features/bails-record-the-decision.feature, e2e/features/bails-send-direction.feature, e2e/features/bails-submit-bail-application-admin-officer.feature, e2e/features/bails-submit-bail-application-home-office.feature, e2e/features/bails-submit-bail-application-legal-rep.feature, e2e/features/bails-upload-bail-summary.feature, e2e/features/bails-upload-documents.feature, e2e/features/bails-upload-signed-decision-notice.feature
=> Bails master

e2e/features/stepDefinitions/ccd-page.steps.ts
=> small change to ccd page steps

e2e/features/stepDefinitions/ccd-page.steps.ts
=> small change

e2e/features/request-respondent-evidence.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/update-legal-representatives-details.feature, e2e/features/upload-additional-evidence-home-office.feature
=> temp commenting out for when/if these are switched back to PA

e2e/features/bails-submit-bail-application-legal-rep.feature, e2e/features/submit-appeal.feature
=> fix for safari mac xbrowser

e2e/features/bails-submit-bail-application-legal-rep.feature, e2e/features/submit-appeal.feature
=> X browser fix

e2e/features/end-appeal.feature, e2e/features/start-decisions-and-reasons.feature, e2e/features/upload-additional-evidence-home-office.feature
=> added wait time to avoid failure due to spinner

e2e/features/bails-make-new-application.feature, e2e/features/stepDefinitions/service/bails-add-a-case-note.steps.ts, e2e/flows/bails-add-a-case-note.flow.ts
=> added case note retaining test

e2e/features/bails-end-application.feature, e2e/flows/request-respondent-evidence.flow.ts
=> Fixes 11 10 22 master

e2e/features/bails-add-a-case-note.feature, e2e/features/bails-end-application.feature, e2e/features/bails-make-new-application.feature, e2e/features/bails-submit-bail-application-legal-rep.feature, e2e/features/bails-upload-signed-decision-notice.feature, e2e/features/start-decisions-and-reasons.feature, e2e/flows/bails-edit-bail-application-post-submit.flow.ts
=> Bails update master

e2e/features/stepDefinitions/allocate-a-role.steps.ts, e2e/features/wa-iac-exclusions.feature, e2e/features/wa-iac-judicial.feature, e2e/features/wa-iac-legal-ops.feature, e2e/flows/allocate-a-role.flow.ts, e2e/flows/exclusions.flow.ts
=> WA test fixes

e2e/features/bails-submit-bail-application-legal-rep.feature, e2e/features/legal-rep-online-payments-pay-by-card-eu-appeal.feature, e2e/features/legal-rep-online-payments-pay-by-pba-eu-appeal.feature, e2e/flows/start-appeal.flow.ts
=> DO NOT MERGE (master) until EUSS merged into master

yarn.lock
=> fix for build failures

e2e/features/add-case-note.feature, e2e/features/end-appeal.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/stepDefinitions/service/submit-appeal.steps.ts, e2e/features/submit-appeal.feature, e2e/flows/submit-appeal.flow.ts, e2e/pages/any.page.ts
=> Pipeline failures Submit Appeal flow 

Jenkinsfile_nightly, e2e/features/add-case-note.feature, e2e/features/bails-submit-bail-application-legal-rep.feature, e2e/features/end-appeal.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/features/stepDefinitions/service/submit-appeal.steps.ts, e2e/features/submit-appeal.feature, e2e/flows/submit-appeal.flow.ts, e2e/pages/any.page.ts, yarn.lock
=> Fix pipeline failures

.yarnrc.yml
=> DIAC-48 fix

Jenkinsfile_nightly
=> updating Jenkinsfile_nightly

e2e/ia.conf.js
=> removing hardcoded test account and updated secrets accordingly

e2e/flows/list-case.flow.ts
=> list case updated

e2e/features/decide-an-application.feature, e2e/features/dlrm/set-aside-correct-decision-under-31.feature
=> added tag to dlrm test and deprecated old test.

e2e/features/dlrm/remitted.feature
=> Remitted feature tests

e2e/features/dlrm/remitted.feature
=> adding tag and fixes

e2e/features/dlrm/remitted.feature
=> to fix undefined step in remitted feature

e2e/features/bails-snl-admin-request-a-hearing.feature, e2e/features/bails-snl-ho-request-a-hearing.feature, e2e/features/bails-snl-lr-request-a-hearing.feature, e2e/features/bails-submit-bail-application-admin-officer.feature, e2e/features/bails-submit-bail-application-home-office.feature, e2e/features/bails-submit-bail-application-legal-rep.feature, e2e/features/bails-update-interpreter-details-status.feature, e2e/features/bails-update-interpreter-details.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/flows/submit-hearing-requirements.flow.ts
=> updated tags and case type to national rollout e2e

e2e/features/bails-snl-admin-request-a-hearing.feature, e2e/features/bails-snl-ho-request-a-hearing.feature, e2e/features/bails-snl-lr-request-a-hearing.feature, e2e/features/bails-submit-bail-application-admin-officer.feature, e2e/features/bails-submit-bail-application-home-office.feature, e2e/features/bails-submit-bail-application-legal-rep.feature, e2e/features/bails-update-interpreter-details-status.feature, e2e/features/bails-update-interpreter-details.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/flows/submit-hearing-requirements.flow.ts
=> National roll out revert case type to master

e2e/features/stepDefinitions/ccd-page.steps.ts
=> case type change to master

e2e/features/bails-edit-application-post-submit.feature, e2e/features/bails-edit-application-pre-submit.feature, e2e/flows/bails-edit-bail-application-post-submit.flow.ts, e2e/flows/bails-edit-bail-application-pre-submit.flow.ts, e2e/flows/bails-make-new-application.flow.ts, e2e/flows/bails-start-bail-application.flow.ts
=> bail management update

e2e/features/edit-case-listing.feature, e2e/features/list-case.feature, e2e/features/snl-pa-request-a-hearing.feature, e2e/features/snl-rp-request-a-hearing.feature, e2e/flows/list-case.flow.ts
=> Updated Automation for SNL Ref data

e2e/features/manage-fee-update-dlrm.feature, e2e/features/stepDefinitions/ccd-page.steps.ts, e2e/flows/mark-appeal-as-paid.flow.ts, e2e/flows/record-remission-decision.flow.ts
DLRM Manage a fee update changes to xui automated test 
[mfu-automated-test.pdf](https://github.com/user-attachments/files/16707045/mfu-automated-test.pdf)
- [] Does this PR introduce a breaking change
=> manage-a-fee-update-dlrm-changes.

e2e/pages/ccd.page.ts
=> Update browser cookie

e2e/flows/pay-and-submit-appeal.flow.ts, e2e/flows/start-appeal.flow.ts
=> DIAC-899: Updated content and flows

e2e/flows/add-appeal-response.flow.ts, e2e/flows/build-case.flow.ts, e2e/flows/create-case-summary.flow.ts, e2e/flows/submit-appeal.flow.ts, e2e/flows/upload-respondent-evidence.flow.ts, e2e/pages/ccd-form.page.ts
=> To fix upload issue across flows

e2e/features.parallel.linux.conf.js, e2e/features.parallel.mac.conf.js, e2e/features.parallel.windows.conf.js
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> fix for after hook

package.json, yarn.lock
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> DIAC-1451 CVE fix

e2e/pages/ccd.page.ts
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> xbrowser fix
